// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/initial_environment.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializehandshakeAck")
public inline fun handshakeAck(block: com.kyhsgeekcode.minecraftenv.proto.HandshakeAckKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.HandshakeAck =
  com.kyhsgeekcode.minecraftenv.proto.HandshakeAckKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.HandshakeAck.newBuilder()).apply { block() }._build()
/**
 * ```
 * Sent by Java right after it reads InitialEnvironmentMessage, before entering the world -
 * lets Python reject an incompatible server immediately instead of hanging on the first
 * read_observation() call or crashing Java mid-init. One per session, so no perf constraint
 * (docs/26_2_MigrationPlan.md item (f)).
 * ```
 *
 * Protobuf type `HandshakeAck`
 */
public object HandshakeAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.HandshakeAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.HandshakeAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.HandshakeAck = _builder.build()

    /**
     * ```
     * CRAFTGROUND_PROTOCOL_VERSION the Java side implements
     * ```
     *
     * `int32 protocol_version = 1;`
     */
    public var protocolVersion: kotlin.Int
      @JvmName("getProtocolVersion")
      get() = _builder.protocolVersion
      @JvmName("setProtocolVersion")
      set(value) {
        _builder.protocolVersion = value
      }
    /**
     * ```
     * CRAFTGROUND_PROTOCOL_VERSION the Java side implements
     * ```
     *
     * `int32 protocol_version = 1;`
     */
    public fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }

    /**
     * ```
     * e.g. "1.21" or "26.2"
     * ```
     *
     * `string minecraft_version = 2;`
     */
    public var minecraftVersion: kotlin.String
      @JvmName("getMinecraftVersion")
      get() = _builder.minecraftVersion
      @JvmName("setMinecraftVersion")
      set(value) {
        _builder.minecraftVersion = value
      }
    /**
     * ```
     * e.g. "1.21" or "26.2"
     * ```
     *
     * `string minecraft_version = 2;`
     */
    public fun clearMinecraftVersion() {
      _builder.clearMinecraftVersion()
    }

    /**
     * ```
     * e.g. "opengl", "vulkan-cpu-readback", "vulkan-zerocopy-metal", "vulkan-zerocopy-cuda"
     * ```
     *
     * `string render_backend = 3;`
     */
    public var renderBackend: kotlin.String
      @JvmName("getRenderBackend")
      get() = _builder.renderBackend
      @JvmName("setRenderBackend")
      set(value) {
        _builder.renderBackend = value
      }
    /**
     * ```
     * e.g. "opengl", "vulkan-cpu-readback", "vulkan-zerocopy-metal", "vulkan-zerocopy-cuda"
     * ```
     *
     * `string render_backend = 3;`
     */
    public fun clearRenderBackend() {
      _builder.clearRenderBackend()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CapabilitiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * e.g. "zerocopy_gl", "zerocopy_metal", "zerocopy_cuda", "depth"
     * ```
     *
     * `repeated string capabilities = 4;`
     * @return A list containing the capabilities.
     */
    public val capabilities: com.google.protobuf.kotlin.DslList<kotlin.String, CapabilitiesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.capabilitiesList
      )
    /**
     * ```
     * e.g. "zerocopy_gl", "zerocopy_metal", "zerocopy_cuda", "depth"
     * ```
     *
     * `repeated string capabilities = 4;`
     * @param value The capabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCapabilities")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CapabilitiesProxy>.add(value: kotlin.String) {
      _builder.addCapabilities(value)
    }
    /**
     * ```
     * e.g. "zerocopy_gl", "zerocopy_metal", "zerocopy_cuda", "depth"
     * ```
     *
     * `repeated string capabilities = 4;`
     * @param value The capabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCapabilities")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CapabilitiesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * e.g. "zerocopy_gl", "zerocopy_metal", "zerocopy_cuda", "depth"
     * ```
     *
     * `repeated string capabilities = 4;`
     * @param values The capabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCapabilities")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CapabilitiesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllCapabilities(values)
    }
    /**
     * ```
     * e.g. "zerocopy_gl", "zerocopy_metal", "zerocopy_cuda", "depth"
     * ```
     *
     * `repeated string capabilities = 4;`
     * @param values The capabilities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCapabilities")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CapabilitiesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * e.g. "zerocopy_gl", "zerocopy_metal", "zerocopy_cuda", "depth"
     * ```
     *
     * `repeated string capabilities = 4;`
     * @param index The index to set the value at.
     * @param value The capabilities to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCapabilities")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CapabilitiesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setCapabilities(index, value)
    }/**
     * ```
     * e.g. "zerocopy_gl", "zerocopy_metal", "zerocopy_cuda", "depth"
     * ```
     *
     * `repeated string capabilities = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCapabilities")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CapabilitiesProxy>.clear() {
      _builder.clearCapabilities()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.HandshakeAck.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.HandshakeAckKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.HandshakeAck =
  `com.kyhsgeekcode.minecraftenv.proto`.HandshakeAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

