// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializeheightInfo")
public inline fun heightInfo(block: com.kyhsgeekcode.minecraftenv.proto.HeightInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo =
  com.kyhsgeekcode.minecraftenv.proto.HeightInfoKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `HeightInfo`
 */
public object HeightInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo = _builder.build()

    /**
     * `int32 x = 1;`
     */
    public var x: kotlin.Int
      @JvmName("getX")
      get() = _builder.x
      @JvmName("setX")
      set(value) {
        _builder.x = value
      }
    /**
     * `int32 x = 1;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `int32 z = 2;`
     */
    public var z: kotlin.Int
      @JvmName("getZ")
      get() = _builder.z
      @JvmName("setZ")
      set(value) {
        _builder.z = value
      }
    /**
     * `int32 z = 2;`
     */
    public fun clearZ() {
      _builder.clearZ()
    }

    /**
     * `int32 height = 3;`
     */
    public var height: kotlin.Int
      @JvmName("getHeight")
      get() = _builder.height
      @JvmName("setHeight")
      set(value) {
        _builder.height = value
      }
    /**
     * `int32 height = 3;`
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * `string block_name = 4;`
     */
    public var blockName: kotlin.String
      @JvmName("getBlockName")
      get() = _builder.blockName
      @JvmName("setBlockName")
      set(value) {
        _builder.blockName = value
      }
    /**
     * `string block_name = 4;`
     */
    public fun clearBlockName() {
      _builder.clearBlockName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.HeightInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo =
  `com.kyhsgeekcode.minecraftenv.proto`.HeightInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

