// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/initial_environment.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializelidarConfig")
public inline fun lidarConfig(block: com.kyhsgeekcode.minecraftenv.proto.LidarConfigKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.LidarConfig =
  com.kyhsgeekcode.minecraftenv.proto.LidarConfigKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.LidarConfig.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `LidarConfig`
 */
public object LidarConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.LidarConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.LidarConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.LidarConfig = _builder.build()

    /**
     * ```
     * Number of rays in the horizontal plane (e.g., 32 for 32 rays around 360 degrees)
     * ```
     *
     * `int32 horizontal_rays = 1;`
     */
    public var horizontalRays: kotlin.Int
      @JvmName("getHorizontalRays")
      get() = _builder.horizontalRays
      @JvmName("setHorizontalRays")
      set(value) {
        _builder.horizontalRays = value
      }
    /**
     * ```
     * Number of rays in the horizontal plane (e.g., 32 for 32 rays around 360 degrees)
     * ```
     *
     * `int32 horizontal_rays = 1;`
     */
    public fun clearHorizontalRays() {
      _builder.clearHorizontalRays()
    }

    /**
     * ```
     * Maximum raycast distance in blocks (e.g., 100.0)
     * ```
     *
     * `float max_distance = 2;`
     */
    public var maxDistance: kotlin.Float
      @JvmName("getMaxDistance")
      get() = _builder.maxDistance
      @JvmName("setMaxDistance")
      set(value) {
        _builder.maxDistance = value
      }
    /**
     * ```
     * Maximum raycast distance in blocks (e.g., 100.0)
     * ```
     *
     * `float max_distance = 2;`
     */
    public fun clearMaxDistance() {
      _builder.clearMaxDistance()
    }

    /**
     * ```
     * Vertical angle offset from horizontal plane in degrees (0.0 = horizontal)
     * ```
     *
     * `float vertical_angle = 3;`
     */
    public var verticalAngle: kotlin.Float
      @JvmName("getVerticalAngle")
      get() = _builder.verticalAngle
      @JvmName("setVerticalAngle")
      set(value) {
        _builder.verticalAngle = value
      }
    /**
     * ```
     * Vertical angle offset from horizontal plane in degrees (0.0 = horizontal)
     * ```
     *
     * `float vertical_angle = 3;`
     */
    public fun clearVerticalAngle() {
      _builder.clearVerticalAngle()
    }

    /**
     * ```
     * Number of vertical ray layers (default 1 for single horizontal plane)
     * ```
     *
     * `int32 vertical_rays = 4;`
     */
    public var verticalRays: kotlin.Int
      @JvmName("getVerticalRays")
      get() = _builder.verticalRays
      @JvmName("setVerticalRays")
      set(value) {
        _builder.verticalRays = value
      }
    /**
     * ```
     * Number of vertical ray layers (default 1 for single horizontal plane)
     * ```
     *
     * `int32 vertical_rays = 4;`
     */
    public fun clearVerticalRays() {
      _builder.clearVerticalRays()
    }

    /**
     * ```
     * Vertical field of view in degrees (e.g., 30.0 for +/- 15 degrees)
     * ```
     *
     * `float vertical_fov = 5;`
     */
    public var verticalFov: kotlin.Float
      @JvmName("getVerticalFov")
      get() = _builder.verticalFov
      @JvmName("setVerticalFov")
      set(value) {
        _builder.verticalFov = value
      }
    /**
     * ```
     * Vertical field of view in degrees (e.g., 30.0 for +/- 15 degrees)
     * ```
     *
     * `float vertical_fov = 5;`
     */
    public fun clearVerticalFov() {
      _builder.clearVerticalFov()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.LidarConfig.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.LidarConfigKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.InitialEnvironment.LidarConfig =
  `com.kyhsgeekcode.minecraftenv.proto`.LidarConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

