from .action import ActionWrapper
from .attack_kill import AttackKillWrapper
from .avoid_damage import AvoidDamageWrapper
from .bimodal import BimodalWrapper
from .bimodal_token import BimodalTokenWrapper
from .fish_cod import FishCodWrapper
from .mineclip import MineCLIPRewardWrapper
from .sound import SoundWrapper
from .terminate_on_death import TerminateOnDeathWrapper
from .vision import VisionWrapper
