// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/action_space.proto
// Protobuf Java Version: 4.29.1

package com.kyhsgeekcode.minecraftenv.proto;

public final class ActionSpace {
  private ActionSpace() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      ActionSpace.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ActionSpaceMessageV2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActionSpaceMessageV2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Discrete actions for movement and other commands as bool
     * </pre>
     *
     * <code>bool attack = 1;</code>
     * @return The attack.
     */
    boolean getAttack();

    /**
     * <code>bool back = 2;</code>
     * @return The back.
     */
    boolean getBack();

    /**
     * <code>bool forward = 3;</code>
     * @return The forward.
     */
    boolean getForward();

    /**
     * <code>bool jump = 4;</code>
     * @return The jump.
     */
    boolean getJump();

    /**
     * <code>bool left = 5;</code>
     * @return The left.
     */
    boolean getLeft();

    /**
     * <code>bool right = 6;</code>
     * @return The right.
     */
    boolean getRight();

    /**
     * <code>bool sneak = 7;</code>
     * @return The sneak.
     */
    boolean getSneak();

    /**
     * <code>bool sprint = 8;</code>
     * @return The sprint.
     */
    boolean getSprint();

    /**
     * <code>bool use = 9;</code>
     * @return The use.
     */
    boolean getUse();

    /**
     * <code>bool drop = 10;</code>
     * @return The drop.
     */
    boolean getDrop();

    /**
     * <code>bool inventory = 11;</code>
     * @return The inventory.
     */
    boolean getInventory();

    /**
     * <pre>
     * Hotbar selection (1-9) as bool
     * </pre>
     *
     * <code>bool hotbar_1 = 12;</code>
     * @return The hotbar1.
     */
    boolean getHotbar1();

    /**
     * <code>bool hotbar_2 = 13;</code>
     * @return The hotbar2.
     */
    boolean getHotbar2();

    /**
     * <code>bool hotbar_3 = 14;</code>
     * @return The hotbar3.
     */
    boolean getHotbar3();

    /**
     * <code>bool hotbar_4 = 15;</code>
     * @return The hotbar4.
     */
    boolean getHotbar4();

    /**
     * <code>bool hotbar_5 = 16;</code>
     * @return The hotbar5.
     */
    boolean getHotbar5();

    /**
     * <code>bool hotbar_6 = 17;</code>
     * @return The hotbar6.
     */
    boolean getHotbar6();

    /**
     * <code>bool hotbar_7 = 18;</code>
     * @return The hotbar7.
     */
    boolean getHotbar7();

    /**
     * <code>bool hotbar_8 = 19;</code>
     * @return The hotbar8.
     */
    boolean getHotbar8();

    /**
     * <code>bool hotbar_9 = 20;</code>
     * @return The hotbar9.
     */
    boolean getHotbar9();

    /**
     * <pre>
     * Camera movement (pitch and yaw)
     * </pre>
     *
     * <code>float camera_pitch = 21;</code>
     * @return The cameraPitch.
     */
    float getCameraPitch();

    /**
     * <code>float camera_yaw = 22;</code>
     * @return The cameraYaw.
     */
    float getCameraYaw();

    /**
     * <code>repeated string commands = 23;</code>
     * @return A list containing the commands.
     */
    java.util.List<java.lang.String>
        getCommandsList();
    /**
     * <code>repeated string commands = 23;</code>
     * @return The count of commands.
     */
    int getCommandsCount();
    /**
     * <code>repeated string commands = 23;</code>
     * @param index The index of the element to return.
     * @return The commands at the given index.
     */
    java.lang.String getCommands(int index);
    /**
     * <code>repeated string commands = 23;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commands at the given index.
     */
    com.google.protobuf.ByteString
        getCommandsBytes(int index);
  }
  /**
   * Protobuf type {@code ActionSpaceMessageV2}
   */
  public static final class ActionSpaceMessageV2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ActionSpaceMessageV2)
      ActionSpaceMessageV2OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        ActionSpaceMessageV2.class.getName());
    }
    // Use ActionSpaceMessageV2.newBuilder() to construct.
    private ActionSpaceMessageV2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ActionSpaceMessageV2() {
      commands_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kyhsgeekcode.minecraftenv.proto.ActionSpace.internal_static_ActionSpaceMessageV2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kyhsgeekcode.minecraftenv.proto.ActionSpace.internal_static_ActionSpaceMessageV2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2.class, com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2.Builder.class);
    }

    public static final int ATTACK_FIELD_NUMBER = 1;
    private boolean attack_ = false;
    /**
     * <pre>
     * Discrete actions for movement and other commands as bool
     * </pre>
     *
     * <code>bool attack = 1;</code>
     * @return The attack.
     */
    @java.lang.Override
    public boolean getAttack() {
      return attack_;
    }

    public static final int BACK_FIELD_NUMBER = 2;
    private boolean back_ = false;
    /**
     * <code>bool back = 2;</code>
     * @return The back.
     */
    @java.lang.Override
    public boolean getBack() {
      return back_;
    }

    public static final int FORWARD_FIELD_NUMBER = 3;
    private boolean forward_ = false;
    /**
     * <code>bool forward = 3;</code>
     * @return The forward.
     */
    @java.lang.Override
    public boolean getForward() {
      return forward_;
    }

    public static final int JUMP_FIELD_NUMBER = 4;
    private boolean jump_ = false;
    /**
     * <code>bool jump = 4;</code>
     * @return The jump.
     */
    @java.lang.Override
    public boolean getJump() {
      return jump_;
    }

    public static final int LEFT_FIELD_NUMBER = 5;
    private boolean left_ = false;
    /**
     * <code>bool left = 5;</code>
     * @return The left.
     */
    @java.lang.Override
    public boolean getLeft() {
      return left_;
    }

    public static final int RIGHT_FIELD_NUMBER = 6;
    private boolean right_ = false;
    /**
     * <code>bool right = 6;</code>
     * @return The right.
     */
    @java.lang.Override
    public boolean getRight() {
      return right_;
    }

    public static final int SNEAK_FIELD_NUMBER = 7;
    private boolean sneak_ = false;
    /**
     * <code>bool sneak = 7;</code>
     * @return The sneak.
     */
    @java.lang.Override
    public boolean getSneak() {
      return sneak_;
    }

    public static final int SPRINT_FIELD_NUMBER = 8;
    private boolean sprint_ = false;
    /**
     * <code>bool sprint = 8;</code>
     * @return The sprint.
     */
    @java.lang.Override
    public boolean getSprint() {
      return sprint_;
    }

    public static final int USE_FIELD_NUMBER = 9;
    private boolean use_ = false;
    /**
     * <code>bool use = 9;</code>
     * @return The use.
     */
    @java.lang.Override
    public boolean getUse() {
      return use_;
    }

    public static final int DROP_FIELD_NUMBER = 10;
    private boolean drop_ = false;
    /**
     * <code>bool drop = 10;</code>
     * @return The drop.
     */
    @java.lang.Override
    public boolean getDrop() {
      return drop_;
    }

    public static final int INVENTORY_FIELD_NUMBER = 11;
    private boolean inventory_ = false;
    /**
     * <code>bool inventory = 11;</code>
     * @return The inventory.
     */
    @java.lang.Override
    public boolean getInventory() {
      return inventory_;
    }

    public static final int HOTBAR_1_FIELD_NUMBER = 12;
    private boolean hotbar1_ = false;
    /**
     * <pre>
     * Hotbar selection (1-9) as bool
     * </pre>
     *
     * <code>bool hotbar_1 = 12;</code>
     * @return The hotbar1.
     */
    @java.lang.Override
    public boolean getHotbar1() {
      return hotbar1_;
    }

    public static final int HOTBAR_2_FIELD_NUMBER = 13;
    private boolean hotbar2_ = false;
    /**
     * <code>bool hotbar_2 = 13;</code>
     * @return The hotbar2.
     */
    @java.lang.Override
    public boolean getHotbar2() {
      return hotbar2_;
    }

    public static final int HOTBAR_3_FIELD_NUMBER = 14;
    private boolean hotbar3_ = false;
    /**
     * <code>bool hotbar_3 = 14;</code>
     * @return The hotbar3.
     */
    @java.lang.Override
    public boolean getHotbar3() {
      return hotbar3_;
    }

    public static final int HOTBAR_4_FIELD_NUMBER = 15;
    private boolean hotbar4_ = false;
    /**
     * <code>bool hotbar_4 = 15;</code>
     * @return The hotbar4.
     */
    @java.lang.Override
    public boolean getHotbar4() {
      return hotbar4_;
    }

    public static final int HOTBAR_5_FIELD_NUMBER = 16;
    private boolean hotbar5_ = false;
    /**
     * <code>bool hotbar_5 = 16;</code>
     * @return The hotbar5.
     */
    @java.lang.Override
    public boolean getHotbar5() {
      return hotbar5_;
    }

    public static final int HOTBAR_6_FIELD_NUMBER = 17;
    private boolean hotbar6_ = false;
    /**
     * <code>bool hotbar_6 = 17;</code>
     * @return The hotbar6.
     */
    @java.lang.Override
    public boolean getHotbar6() {
      return hotbar6_;
    }

    public static final int HOTBAR_7_FIELD_NUMBER = 18;
    private boolean hotbar7_ = false;
    /**
     * <code>bool hotbar_7 = 18;</code>
     * @return The hotbar7.
     */
    @java.lang.Override
    public boolean getHotbar7() {
      return hotbar7_;
    }

    public static final int HOTBAR_8_FIELD_NUMBER = 19;
    private boolean hotbar8_ = false;
    /**
     * <code>bool hotbar_8 = 19;</code>
     * @return The hotbar8.
     */
    @java.lang.Override
    public boolean getHotbar8() {
      return hotbar8_;
    }

    public static final int HOTBAR_9_FIELD_NUMBER = 20;
    private boolean hotbar9_ = false;
    /**
     * <code>bool hotbar_9 = 20;</code>
     * @return The hotbar9.
     */
    @java.lang.Override
    public boolean getHotbar9() {
      return hotbar9_;
    }

    public static final int CAMERA_PITCH_FIELD_NUMBER = 21;
    private float cameraPitch_ = 0F;
    /**
     * <pre>
     * Camera movement (pitch and yaw)
     * </pre>
     *
     * <code>float camera_pitch = 21;</code>
     * @return The cameraPitch.
     */
    @java.lang.Override
    public float getCameraPitch() {
      return cameraPitch_;
    }

    public static final int CAMERA_YAW_FIELD_NUMBER = 22;
    private float cameraYaw_ = 0F;
    /**
     * <code>float camera_yaw = 22;</code>
     * @return The cameraYaw.
     */
    @java.lang.Override
    public float getCameraYaw() {
      return cameraYaw_;
    }

    public static final int COMMANDS_FIELD_NUMBER = 23;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList commands_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string commands = 23;</code>
     * @return A list containing the commands.
     */
    public com.google.protobuf.ProtocolStringList
        getCommandsList() {
      return commands_;
    }
    /**
     * <code>repeated string commands = 23;</code>
     * @return The count of commands.
     */
    public int getCommandsCount() {
      return commands_.size();
    }
    /**
     * <code>repeated string commands = 23;</code>
     * @param index The index of the element to return.
     * @return The commands at the given index.
     */
    public java.lang.String getCommands(int index) {
      return commands_.get(index);
    }
    /**
     * <code>repeated string commands = 23;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commands at the given index.
     */
    public com.google.protobuf.ByteString
        getCommandsBytes(int index) {
      return commands_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (attack_ != false) {
        output.writeBool(1, attack_);
      }
      if (back_ != false) {
        output.writeBool(2, back_);
      }
      if (forward_ != false) {
        output.writeBool(3, forward_);
      }
      if (jump_ != false) {
        output.writeBool(4, jump_);
      }
      if (left_ != false) {
        output.writeBool(5, left_);
      }
      if (right_ != false) {
        output.writeBool(6, right_);
      }
      if (sneak_ != false) {
        output.writeBool(7, sneak_);
      }
      if (sprint_ != false) {
        output.writeBool(8, sprint_);
      }
      if (use_ != false) {
        output.writeBool(9, use_);
      }
      if (drop_ != false) {
        output.writeBool(10, drop_);
      }
      if (inventory_ != false) {
        output.writeBool(11, inventory_);
      }
      if (hotbar1_ != false) {
        output.writeBool(12, hotbar1_);
      }
      if (hotbar2_ != false) {
        output.writeBool(13, hotbar2_);
      }
      if (hotbar3_ != false) {
        output.writeBool(14, hotbar3_);
      }
      if (hotbar4_ != false) {
        output.writeBool(15, hotbar4_);
      }
      if (hotbar5_ != false) {
        output.writeBool(16, hotbar5_);
      }
      if (hotbar6_ != false) {
        output.writeBool(17, hotbar6_);
      }
      if (hotbar7_ != false) {
        output.writeBool(18, hotbar7_);
      }
      if (hotbar8_ != false) {
        output.writeBool(19, hotbar8_);
      }
      if (hotbar9_ != false) {
        output.writeBool(20, hotbar9_);
      }
      if (java.lang.Float.floatToRawIntBits(cameraPitch_) != 0) {
        output.writeFloat(21, cameraPitch_);
      }
      if (java.lang.Float.floatToRawIntBits(cameraYaw_) != 0) {
        output.writeFloat(22, cameraYaw_);
      }
      for (int i = 0; i < commands_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 23, commands_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (attack_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, attack_);
      }
      if (back_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, back_);
      }
      if (forward_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, forward_);
      }
      if (jump_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, jump_);
      }
      if (left_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, left_);
      }
      if (right_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, right_);
      }
      if (sneak_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, sneak_);
      }
      if (sprint_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, sprint_);
      }
      if (use_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, use_);
      }
      if (drop_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, drop_);
      }
      if (inventory_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, inventory_);
      }
      if (hotbar1_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, hotbar1_);
      }
      if (hotbar2_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, hotbar2_);
      }
      if (hotbar3_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, hotbar3_);
      }
      if (hotbar4_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, hotbar4_);
      }
      if (hotbar5_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, hotbar5_);
      }
      if (hotbar6_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(17, hotbar6_);
      }
      if (hotbar7_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(18, hotbar7_);
      }
      if (hotbar8_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(19, hotbar8_);
      }
      if (hotbar9_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20, hotbar9_);
      }
      if (java.lang.Float.floatToRawIntBits(cameraPitch_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(21, cameraPitch_);
      }
      if (java.lang.Float.floatToRawIntBits(cameraYaw_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(22, cameraYaw_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < commands_.size(); i++) {
          dataSize += computeStringSizeNoTag(commands_.getRaw(i));
        }
        size += dataSize;
        size += 2 * getCommandsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2)) {
        return super.equals(obj);
      }
      com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 other = (com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2) obj;

      if (getAttack()
          != other.getAttack()) return false;
      if (getBack()
          != other.getBack()) return false;
      if (getForward()
          != other.getForward()) return false;
      if (getJump()
          != other.getJump()) return false;
      if (getLeft()
          != other.getLeft()) return false;
      if (getRight()
          != other.getRight()) return false;
      if (getSneak()
          != other.getSneak()) return false;
      if (getSprint()
          != other.getSprint()) return false;
      if (getUse()
          != other.getUse()) return false;
      if (getDrop()
          != other.getDrop()) return false;
      if (getInventory()
          != other.getInventory()) return false;
      if (getHotbar1()
          != other.getHotbar1()) return false;
      if (getHotbar2()
          != other.getHotbar2()) return false;
      if (getHotbar3()
          != other.getHotbar3()) return false;
      if (getHotbar4()
          != other.getHotbar4()) return false;
      if (getHotbar5()
          != other.getHotbar5()) return false;
      if (getHotbar6()
          != other.getHotbar6()) return false;
      if (getHotbar7()
          != other.getHotbar7()) return false;
      if (getHotbar8()
          != other.getHotbar8()) return false;
      if (getHotbar9()
          != other.getHotbar9()) return false;
      if (java.lang.Float.floatToIntBits(getCameraPitch())
          != java.lang.Float.floatToIntBits(
              other.getCameraPitch())) return false;
      if (java.lang.Float.floatToIntBits(getCameraYaw())
          != java.lang.Float.floatToIntBits(
              other.getCameraYaw())) return false;
      if (!getCommandsList()
          .equals(other.getCommandsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ATTACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAttack());
      hash = (37 * hash) + BACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBack());
      hash = (37 * hash) + FORWARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getForward());
      hash = (37 * hash) + JUMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getJump());
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLeft());
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRight());
      hash = (37 * hash) + SNEAK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSneak());
      hash = (37 * hash) + SPRINT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSprint());
      hash = (37 * hash) + USE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUse());
      hash = (37 * hash) + DROP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDrop());
      hash = (37 * hash) + INVENTORY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getInventory());
      hash = (37 * hash) + HOTBAR_1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar1());
      hash = (37 * hash) + HOTBAR_2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar2());
      hash = (37 * hash) + HOTBAR_3_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar3());
      hash = (37 * hash) + HOTBAR_4_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar4());
      hash = (37 * hash) + HOTBAR_5_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar5());
      hash = (37 * hash) + HOTBAR_6_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar6());
      hash = (37 * hash) + HOTBAR_7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar7());
      hash = (37 * hash) + HOTBAR_8_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar8());
      hash = (37 * hash) + HOTBAR_9_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHotbar9());
      hash = (37 * hash) + CAMERA_PITCH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCameraPitch());
      hash = (37 * hash) + CAMERA_YAW_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCameraYaw());
      if (getCommandsCount() > 0) {
        hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
        hash = (53 * hash) + getCommandsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ActionSpaceMessageV2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActionSpaceMessageV2)
        com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kyhsgeekcode.minecraftenv.proto.ActionSpace.internal_static_ActionSpaceMessageV2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kyhsgeekcode.minecraftenv.proto.ActionSpace.internal_static_ActionSpaceMessageV2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2.class, com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2.Builder.class);
      }

      // Construct using com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        attack_ = false;
        back_ = false;
        forward_ = false;
        jump_ = false;
        left_ = false;
        right_ = false;
        sneak_ = false;
        sprint_ = false;
        use_ = false;
        drop_ = false;
        inventory_ = false;
        hotbar1_ = false;
        hotbar2_ = false;
        hotbar3_ = false;
        hotbar4_ = false;
        hotbar5_ = false;
        hotbar6_ = false;
        hotbar7_ = false;
        hotbar8_ = false;
        hotbar9_ = false;
        cameraPitch_ = 0F;
        cameraYaw_ = 0F;
        commands_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kyhsgeekcode.minecraftenv.proto.ActionSpace.internal_static_ActionSpaceMessageV2_descriptor;
      }

      @java.lang.Override
      public com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 getDefaultInstanceForType() {
        return com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2.getDefaultInstance();
      }

      @java.lang.Override
      public com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 build() {
        com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 buildPartial() {
        com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 result = new com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.attack_ = attack_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.back_ = back_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.forward_ = forward_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.jump_ = jump_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.left_ = left_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.right_ = right_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.sneak_ = sneak_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.sprint_ = sprint_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.use_ = use_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.drop_ = drop_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.inventory_ = inventory_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.hotbar1_ = hotbar1_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.hotbar2_ = hotbar2_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.hotbar3_ = hotbar3_;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.hotbar4_ = hotbar4_;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.hotbar5_ = hotbar5_;
        }
        if (((from_bitField0_ & 0x00010000) != 0)) {
          result.hotbar6_ = hotbar6_;
        }
        if (((from_bitField0_ & 0x00020000) != 0)) {
          result.hotbar7_ = hotbar7_;
        }
        if (((from_bitField0_ & 0x00040000) != 0)) {
          result.hotbar8_ = hotbar8_;
        }
        if (((from_bitField0_ & 0x00080000) != 0)) {
          result.hotbar9_ = hotbar9_;
        }
        if (((from_bitField0_ & 0x00100000) != 0)) {
          result.cameraPitch_ = cameraPitch_;
        }
        if (((from_bitField0_ & 0x00200000) != 0)) {
          result.cameraYaw_ = cameraYaw_;
        }
        if (((from_bitField0_ & 0x00400000) != 0)) {
          commands_.makeImmutable();
          result.commands_ = commands_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2) {
          return mergeFrom((com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 other) {
        if (other == com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2.getDefaultInstance()) return this;
        if (other.getAttack() != false) {
          setAttack(other.getAttack());
        }
        if (other.getBack() != false) {
          setBack(other.getBack());
        }
        if (other.getForward() != false) {
          setForward(other.getForward());
        }
        if (other.getJump() != false) {
          setJump(other.getJump());
        }
        if (other.getLeft() != false) {
          setLeft(other.getLeft());
        }
        if (other.getRight() != false) {
          setRight(other.getRight());
        }
        if (other.getSneak() != false) {
          setSneak(other.getSneak());
        }
        if (other.getSprint() != false) {
          setSprint(other.getSprint());
        }
        if (other.getUse() != false) {
          setUse(other.getUse());
        }
        if (other.getDrop() != false) {
          setDrop(other.getDrop());
        }
        if (other.getInventory() != false) {
          setInventory(other.getInventory());
        }
        if (other.getHotbar1() != false) {
          setHotbar1(other.getHotbar1());
        }
        if (other.getHotbar2() != false) {
          setHotbar2(other.getHotbar2());
        }
        if (other.getHotbar3() != false) {
          setHotbar3(other.getHotbar3());
        }
        if (other.getHotbar4() != false) {
          setHotbar4(other.getHotbar4());
        }
        if (other.getHotbar5() != false) {
          setHotbar5(other.getHotbar5());
        }
        if (other.getHotbar6() != false) {
          setHotbar6(other.getHotbar6());
        }
        if (other.getHotbar7() != false) {
          setHotbar7(other.getHotbar7());
        }
        if (other.getHotbar8() != false) {
          setHotbar8(other.getHotbar8());
        }
        if (other.getHotbar9() != false) {
          setHotbar9(other.getHotbar9());
        }
        if (other.getCameraPitch() != 0F) {
          setCameraPitch(other.getCameraPitch());
        }
        if (other.getCameraYaw() != 0F) {
          setCameraYaw(other.getCameraYaw());
        }
        if (!other.commands_.isEmpty()) {
          if (commands_.isEmpty()) {
            commands_ = other.commands_;
            bitField0_ |= 0x00400000;
          } else {
            ensureCommandsIsMutable();
            commands_.addAll(other.commands_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                attack_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                back_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                forward_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                jump_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                left_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                right_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                sneak_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                sprint_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                use_ = input.readBool();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                drop_ = input.readBool();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 88: {
                inventory_ = input.readBool();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 96: {
                hotbar1_ = input.readBool();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              case 104: {
                hotbar2_ = input.readBool();
                bitField0_ |= 0x00001000;
                break;
              } // case 104
              case 112: {
                hotbar3_ = input.readBool();
                bitField0_ |= 0x00002000;
                break;
              } // case 112
              case 120: {
                hotbar4_ = input.readBool();
                bitField0_ |= 0x00004000;
                break;
              } // case 120
              case 128: {
                hotbar5_ = input.readBool();
                bitField0_ |= 0x00008000;
                break;
              } // case 128
              case 136: {
                hotbar6_ = input.readBool();
                bitField0_ |= 0x00010000;
                break;
              } // case 136
              case 144: {
                hotbar7_ = input.readBool();
                bitField0_ |= 0x00020000;
                break;
              } // case 144
              case 152: {
                hotbar8_ = input.readBool();
                bitField0_ |= 0x00040000;
                break;
              } // case 152
              case 160: {
                hotbar9_ = input.readBool();
                bitField0_ |= 0x00080000;
                break;
              } // case 160
              case 173: {
                cameraPitch_ = input.readFloat();
                bitField0_ |= 0x00100000;
                break;
              } // case 173
              case 181: {
                cameraYaw_ = input.readFloat();
                bitField0_ |= 0x00200000;
                break;
              } // case 181
              case 186: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCommandsIsMutable();
                commands_.add(s);
                break;
              } // case 186
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean attack_ ;
      /**
       * <pre>
       * Discrete actions for movement and other commands as bool
       * </pre>
       *
       * <code>bool attack = 1;</code>
       * @return The attack.
       */
      @java.lang.Override
      public boolean getAttack() {
        return attack_;
      }
      /**
       * <pre>
       * Discrete actions for movement and other commands as bool
       * </pre>
       *
       * <code>bool attack = 1;</code>
       * @param value The attack to set.
       * @return This builder for chaining.
       */
      public Builder setAttack(boolean value) {

        attack_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Discrete actions for movement and other commands as bool
       * </pre>
       *
       * <code>bool attack = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttack() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attack_ = false;
        onChanged();
        return this;
      }

      private boolean back_ ;
      /**
       * <code>bool back = 2;</code>
       * @return The back.
       */
      @java.lang.Override
      public boolean getBack() {
        return back_;
      }
      /**
       * <code>bool back = 2;</code>
       * @param value The back to set.
       * @return This builder for chaining.
       */
      public Builder setBack(boolean value) {

        back_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool back = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBack() {
        bitField0_ = (bitField0_ & ~0x00000002);
        back_ = false;
        onChanged();
        return this;
      }

      private boolean forward_ ;
      /**
       * <code>bool forward = 3;</code>
       * @return The forward.
       */
      @java.lang.Override
      public boolean getForward() {
        return forward_;
      }
      /**
       * <code>bool forward = 3;</code>
       * @param value The forward to set.
       * @return This builder for chaining.
       */
      public Builder setForward(boolean value) {

        forward_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool forward = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearForward() {
        bitField0_ = (bitField0_ & ~0x00000004);
        forward_ = false;
        onChanged();
        return this;
      }

      private boolean jump_ ;
      /**
       * <code>bool jump = 4;</code>
       * @return The jump.
       */
      @java.lang.Override
      public boolean getJump() {
        return jump_;
      }
      /**
       * <code>bool jump = 4;</code>
       * @param value The jump to set.
       * @return This builder for chaining.
       */
      public Builder setJump(boolean value) {

        jump_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool jump = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearJump() {
        bitField0_ = (bitField0_ & ~0x00000008);
        jump_ = false;
        onChanged();
        return this;
      }

      private boolean left_ ;
      /**
       * <code>bool left = 5;</code>
       * @return The left.
       */
      @java.lang.Override
      public boolean getLeft() {
        return left_;
      }
      /**
       * <code>bool left = 5;</code>
       * @param value The left to set.
       * @return This builder for chaining.
       */
      public Builder setLeft(boolean value) {

        left_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool left = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeft() {
        bitField0_ = (bitField0_ & ~0x00000010);
        left_ = false;
        onChanged();
        return this;
      }

      private boolean right_ ;
      /**
       * <code>bool right = 6;</code>
       * @return The right.
       */
      @java.lang.Override
      public boolean getRight() {
        return right_;
      }
      /**
       * <code>bool right = 6;</code>
       * @param value The right to set.
       * @return This builder for chaining.
       */
      public Builder setRight(boolean value) {

        right_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bool right = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRight() {
        bitField0_ = (bitField0_ & ~0x00000020);
        right_ = false;
        onChanged();
        return this;
      }

      private boolean sneak_ ;
      /**
       * <code>bool sneak = 7;</code>
       * @return The sneak.
       */
      @java.lang.Override
      public boolean getSneak() {
        return sneak_;
      }
      /**
       * <code>bool sneak = 7;</code>
       * @param value The sneak to set.
       * @return This builder for chaining.
       */
      public Builder setSneak(boolean value) {

        sneak_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool sneak = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSneak() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sneak_ = false;
        onChanged();
        return this;
      }

      private boolean sprint_ ;
      /**
       * <code>bool sprint = 8;</code>
       * @return The sprint.
       */
      @java.lang.Override
      public boolean getSprint() {
        return sprint_;
      }
      /**
       * <code>bool sprint = 8;</code>
       * @param value The sprint to set.
       * @return This builder for chaining.
       */
      public Builder setSprint(boolean value) {

        sprint_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool sprint = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSprint() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sprint_ = false;
        onChanged();
        return this;
      }

      private boolean use_ ;
      /**
       * <code>bool use = 9;</code>
       * @return The use.
       */
      @java.lang.Override
      public boolean getUse() {
        return use_;
      }
      /**
       * <code>bool use = 9;</code>
       * @param value The use to set.
       * @return This builder for chaining.
       */
      public Builder setUse(boolean value) {

        use_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>bool use = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUse() {
        bitField0_ = (bitField0_ & ~0x00000100);
        use_ = false;
        onChanged();
        return this;
      }

      private boolean drop_ ;
      /**
       * <code>bool drop = 10;</code>
       * @return The drop.
       */
      @java.lang.Override
      public boolean getDrop() {
        return drop_;
      }
      /**
       * <code>bool drop = 10;</code>
       * @param value The drop to set.
       * @return This builder for chaining.
       */
      public Builder setDrop(boolean value) {

        drop_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>bool drop = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDrop() {
        bitField0_ = (bitField0_ & ~0x00000200);
        drop_ = false;
        onChanged();
        return this;
      }

      private boolean inventory_ ;
      /**
       * <code>bool inventory = 11;</code>
       * @return The inventory.
       */
      @java.lang.Override
      public boolean getInventory() {
        return inventory_;
      }
      /**
       * <code>bool inventory = 11;</code>
       * @param value The inventory to set.
       * @return This builder for chaining.
       */
      public Builder setInventory(boolean value) {

        inventory_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>bool inventory = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearInventory() {
        bitField0_ = (bitField0_ & ~0x00000400);
        inventory_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar1_ ;
      /**
       * <pre>
       * Hotbar selection (1-9) as bool
       * </pre>
       *
       * <code>bool hotbar_1 = 12;</code>
       * @return The hotbar1.
       */
      @java.lang.Override
      public boolean getHotbar1() {
        return hotbar1_;
      }
      /**
       * <pre>
       * Hotbar selection (1-9) as bool
       * </pre>
       *
       * <code>bool hotbar_1 = 12;</code>
       * @param value The hotbar1 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar1(boolean value) {

        hotbar1_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hotbar selection (1-9) as bool
       * </pre>
       *
       * <code>bool hotbar_1 = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar1() {
        bitField0_ = (bitField0_ & ~0x00000800);
        hotbar1_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar2_ ;
      /**
       * <code>bool hotbar_2 = 13;</code>
       * @return The hotbar2.
       */
      @java.lang.Override
      public boolean getHotbar2() {
        return hotbar2_;
      }
      /**
       * <code>bool hotbar_2 = 13;</code>
       * @param value The hotbar2 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar2(boolean value) {

        hotbar2_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_2 = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar2() {
        bitField0_ = (bitField0_ & ~0x00001000);
        hotbar2_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar3_ ;
      /**
       * <code>bool hotbar_3 = 14;</code>
       * @return The hotbar3.
       */
      @java.lang.Override
      public boolean getHotbar3() {
        return hotbar3_;
      }
      /**
       * <code>bool hotbar_3 = 14;</code>
       * @param value The hotbar3 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar3(boolean value) {

        hotbar3_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_3 = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar3() {
        bitField0_ = (bitField0_ & ~0x00002000);
        hotbar3_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar4_ ;
      /**
       * <code>bool hotbar_4 = 15;</code>
       * @return The hotbar4.
       */
      @java.lang.Override
      public boolean getHotbar4() {
        return hotbar4_;
      }
      /**
       * <code>bool hotbar_4 = 15;</code>
       * @param value The hotbar4 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar4(boolean value) {

        hotbar4_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_4 = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar4() {
        bitField0_ = (bitField0_ & ~0x00004000);
        hotbar4_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar5_ ;
      /**
       * <code>bool hotbar_5 = 16;</code>
       * @return The hotbar5.
       */
      @java.lang.Override
      public boolean getHotbar5() {
        return hotbar5_;
      }
      /**
       * <code>bool hotbar_5 = 16;</code>
       * @param value The hotbar5 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar5(boolean value) {

        hotbar5_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_5 = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar5() {
        bitField0_ = (bitField0_ & ~0x00008000);
        hotbar5_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar6_ ;
      /**
       * <code>bool hotbar_6 = 17;</code>
       * @return The hotbar6.
       */
      @java.lang.Override
      public boolean getHotbar6() {
        return hotbar6_;
      }
      /**
       * <code>bool hotbar_6 = 17;</code>
       * @param value The hotbar6 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar6(boolean value) {

        hotbar6_ = value;
        bitField0_ |= 0x00010000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_6 = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar6() {
        bitField0_ = (bitField0_ & ~0x00010000);
        hotbar6_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar7_ ;
      /**
       * <code>bool hotbar_7 = 18;</code>
       * @return The hotbar7.
       */
      @java.lang.Override
      public boolean getHotbar7() {
        return hotbar7_;
      }
      /**
       * <code>bool hotbar_7 = 18;</code>
       * @param value The hotbar7 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar7(boolean value) {

        hotbar7_ = value;
        bitField0_ |= 0x00020000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_7 = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar7() {
        bitField0_ = (bitField0_ & ~0x00020000);
        hotbar7_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar8_ ;
      /**
       * <code>bool hotbar_8 = 19;</code>
       * @return The hotbar8.
       */
      @java.lang.Override
      public boolean getHotbar8() {
        return hotbar8_;
      }
      /**
       * <code>bool hotbar_8 = 19;</code>
       * @param value The hotbar8 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar8(boolean value) {

        hotbar8_ = value;
        bitField0_ |= 0x00040000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_8 = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar8() {
        bitField0_ = (bitField0_ & ~0x00040000);
        hotbar8_ = false;
        onChanged();
        return this;
      }

      private boolean hotbar9_ ;
      /**
       * <code>bool hotbar_9 = 20;</code>
       * @return The hotbar9.
       */
      @java.lang.Override
      public boolean getHotbar9() {
        return hotbar9_;
      }
      /**
       * <code>bool hotbar_9 = 20;</code>
       * @param value The hotbar9 to set.
       * @return This builder for chaining.
       */
      public Builder setHotbar9(boolean value) {

        hotbar9_ = value;
        bitField0_ |= 0x00080000;
        onChanged();
        return this;
      }
      /**
       * <code>bool hotbar_9 = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearHotbar9() {
        bitField0_ = (bitField0_ & ~0x00080000);
        hotbar9_ = false;
        onChanged();
        return this;
      }

      private float cameraPitch_ ;
      /**
       * <pre>
       * Camera movement (pitch and yaw)
       * </pre>
       *
       * <code>float camera_pitch = 21;</code>
       * @return The cameraPitch.
       */
      @java.lang.Override
      public float getCameraPitch() {
        return cameraPitch_;
      }
      /**
       * <pre>
       * Camera movement (pitch and yaw)
       * </pre>
       *
       * <code>float camera_pitch = 21;</code>
       * @param value The cameraPitch to set.
       * @return This builder for chaining.
       */
      public Builder setCameraPitch(float value) {

        cameraPitch_ = value;
        bitField0_ |= 0x00100000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Camera movement (pitch and yaw)
       * </pre>
       *
       * <code>float camera_pitch = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearCameraPitch() {
        bitField0_ = (bitField0_ & ~0x00100000);
        cameraPitch_ = 0F;
        onChanged();
        return this;
      }

      private float cameraYaw_ ;
      /**
       * <code>float camera_yaw = 22;</code>
       * @return The cameraYaw.
       */
      @java.lang.Override
      public float getCameraYaw() {
        return cameraYaw_;
      }
      /**
       * <code>float camera_yaw = 22;</code>
       * @param value The cameraYaw to set.
       * @return This builder for chaining.
       */
      public Builder setCameraYaw(float value) {

        cameraYaw_ = value;
        bitField0_ |= 0x00200000;
        onChanged();
        return this;
      }
      /**
       * <code>float camera_yaw = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearCameraYaw() {
        bitField0_ = (bitField0_ & ~0x00200000);
        cameraYaw_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList commands_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCommandsIsMutable() {
        if (!commands_.isModifiable()) {
          commands_ = new com.google.protobuf.LazyStringArrayList(commands_);
        }
        bitField0_ |= 0x00400000;
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @return A list containing the commands.
       */
      public com.google.protobuf.ProtocolStringList
          getCommandsList() {
        commands_.makeImmutable();
        return commands_;
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @return The count of commands.
       */
      public int getCommandsCount() {
        return commands_.size();
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @param index The index of the element to return.
       * @return The commands at the given index.
       */
      public java.lang.String getCommands(int index) {
        return commands_.get(index);
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @param index The index of the value to return.
       * @return The bytes of the commands at the given index.
       */
      public com.google.protobuf.ByteString
          getCommandsBytes(int index) {
        return commands_.getByteString(index);
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @param index The index to set the value at.
       * @param value The commands to set.
       * @return This builder for chaining.
       */
      public Builder setCommands(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommandsIsMutable();
        commands_.set(index, value);
        bitField0_ |= 0x00400000;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @param value The commands to add.
       * @return This builder for chaining.
       */
      public Builder addCommands(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommandsIsMutable();
        commands_.add(value);
        bitField0_ |= 0x00400000;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @param values The commands to add.
       * @return This builder for chaining.
       */
      public Builder addAllCommands(
          java.lang.Iterable<java.lang.String> values) {
        ensureCommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commands_);
        bitField0_ |= 0x00400000;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommands() {
        commands_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00400000);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commands = 23;</code>
       * @param value The bytes of the commands to add.
       * @return This builder for chaining.
       */
      public Builder addCommandsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCommandsIsMutable();
        commands_.add(value);
        bitField0_ |= 0x00400000;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ActionSpaceMessageV2)
    }

    // @@protoc_insertion_point(class_scope:ActionSpaceMessageV2)
    private static final com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2();
    }

    public static com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActionSpaceMessageV2>
        PARSER = new com.google.protobuf.AbstractParser<ActionSpaceMessageV2>() {
      @java.lang.Override
      public ActionSpaceMessageV2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ActionSpaceMessageV2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActionSpaceMessageV2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kyhsgeekcode.minecraftenv.proto.ActionSpace.ActionSpaceMessageV2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionSpaceMessageV2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActionSpaceMessageV2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/action_space.proto\"\233\003\n\024ActionSpa" +
      "ceMessageV2\022\016\n\006attack\030\001 \001(\010\022\014\n\004back\030\002 \001(" +
      "\010\022\017\n\007forward\030\003 \001(\010\022\014\n\004jump\030\004 \001(\010\022\014\n\004left" +
      "\030\005 \001(\010\022\r\n\005right\030\006 \001(\010\022\r\n\005sneak\030\007 \001(\010\022\016\n\006" +
      "sprint\030\010 \001(\010\022\013\n\003use\030\t \001(\010\022\014\n\004drop\030\n \001(\010\022" +
      "\021\n\tinventory\030\013 \001(\010\022\020\n\010hotbar_1\030\014 \001(\010\022\020\n\010" +
      "hotbar_2\030\r \001(\010\022\020\n\010hotbar_3\030\016 \001(\010\022\020\n\010hotb" +
      "ar_4\030\017 \001(\010\022\020\n\010hotbar_5\030\020 \001(\010\022\020\n\010hotbar_6" +
      "\030\021 \001(\010\022\020\n\010hotbar_7\030\022 \001(\010\022\020\n\010hotbar_8\030\023 \001" +
      "(\010\022\020\n\010hotbar_9\030\024 \001(\010\022\024\n\014camera_pitch\030\025 \001" +
      "(\002\022\022\n\ncamera_yaw\030\026 \001(\002\022\020\n\010commands\030\027 \003(\t" +
      "B%\n#com.kyhsgeekcode.minecraftenv.protob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ActionSpaceMessageV2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ActionSpaceMessageV2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ActionSpaceMessageV2_descriptor,
        new java.lang.String[] { "Attack", "Back", "Forward", "Jump", "Left", "Right", "Sneak", "Sprint", "Use", "Drop", "Inventory", "Hotbar1", "Hotbar2", "Hotbar3", "Hotbar4", "Hotbar5", "Hotbar6", "Hotbar7", "Hotbar8", "Hotbar9", "CameraPitch", "CameraYaw", "Commands", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
