// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializeaudioWaveform")
public inline fun audioWaveform(block: com.kyhsgeekcode.minecraftenv.proto.AudioWaveformKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.AudioWaveform =
  com.kyhsgeekcode.minecraftenv.proto.AudioWaveformKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.AudioWaveform.newBuilder()).apply { block() }._build()
/**
 * ```
 * Audio waveform data captured via OpenAL SOFT_loopback extension
 * ```
 *
 * Protobuf type `AudioWaveform`
 */
public object AudioWaveformKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.AudioWaveform.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.AudioWaveform.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.AudioWaveform = _builder.build()

    /**
     * ```
     * Raw PCM audio data (16-bit signed, little-endian)
     * ```
     *
     * `bytes pcm_data = 1;`
     */
    public var pcmData: com.google.protobuf.ByteString
      @JvmName("getPcmData")
      get() = _builder.pcmData
      @JvmName("setPcmData")
      set(value) {
        _builder.pcmData = value
      }
    /**
     * ```
     * Raw PCM audio data (16-bit signed, little-endian)
     * ```
     *
     * `bytes pcm_data = 1;`
     */
    public fun clearPcmData() {
      _builder.clearPcmData()
    }

    /**
     * ```
     * Sample rate in Hz (e.g., 44100)
     * ```
     *
     * `int32 sample_rate = 2;`
     */
    public var sampleRate: kotlin.Int
      @JvmName("getSampleRate")
      get() = _builder.sampleRate
      @JvmName("setSampleRate")
      set(value) {
        _builder.sampleRate = value
      }
    /**
     * ```
     * Sample rate in Hz (e.g., 44100)
     * ```
     *
     * `int32 sample_rate = 2;`
     */
    public fun clearSampleRate() {
      _builder.clearSampleRate()
    }

    /**
     * ```
     * Number of channels (1=mono, 2=stereo)
     * ```
     *
     * `int32 channels = 3;`
     */
    public var channels: kotlin.Int
      @JvmName("getChannels")
      get() = _builder.channels
      @JvmName("setChannels")
      set(value) {
        _builder.channels = value
      }
    /**
     * ```
     * Number of channels (1=mono, 2=stereo)
     * ```
     *
     * `int32 channels = 3;`
     */
    public fun clearChannels() {
      _builder.clearChannels()
    }

    /**
     * ```
     * Bits per sample (typically 16)
     * ```
     *
     * `int32 bits_per_sample = 4;`
     */
    public var bitsPerSample: kotlin.Int
      @JvmName("getBitsPerSample")
      get() = _builder.bitsPerSample
      @JvmName("setBitsPerSample")
      set(value) {
        _builder.bitsPerSample = value
      }
    /**
     * ```
     * Bits per sample (typically 16)
     * ```
     *
     * `int32 bits_per_sample = 4;`
     */
    public fun clearBitsPerSample() {
      _builder.clearBitsPerSample()
    }

    /**
     * ```
     * Number of samples per channel in this buffer
     * ```
     *
     * `int32 num_samples = 5;`
     */
    public var numSamples: kotlin.Int
      @JvmName("getNumSamples")
      get() = _builder.numSamples
      @JvmName("setNumSamples")
      set(value) {
        _builder.numSamples = value
      }
    /**
     * ```
     * Number of samples per channel in this buffer
     * ```
     *
     * `int32 num_samples = 5;`
     */
    public fun clearNumSamples() {
      _builder.clearNumSamples()
    }

    /**
     * ```
     * Game tick when this audio was captured
     * ```
     *
     * `int64 timestamp_ticks = 6;`
     */
    public var timestampTicks: kotlin.Long
      @JvmName("getTimestampTicks")
      get() = _builder.timestampTicks
      @JvmName("setTimestampTicks")
      set(value) {
        _builder.timestampTicks = value
      }
    /**
     * ```
     * Game tick when this audio was captured
     * ```
     *
     * `int64 timestamp_ticks = 6;`
     */
    public fun clearTimestampTicks() {
      _builder.clearTimestampTicks()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.AudioWaveform.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.AudioWaveformKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.AudioWaveform =
  `com.kyhsgeekcode.minecraftenv.proto`.AudioWaveformKt.Dsl._create(this.toBuilder()).apply { block() }._build()

