// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializeblockInfo")
public inline fun blockInfo(block: com.kyhsgeekcode.minecraftenv.proto.BlockInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo =
  com.kyhsgeekcode.minecraftenv.proto.BlockInfoKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BlockInfo`
 */
public object BlockInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo = _builder.build()

    /**
     * `int32 x = 1;`
     */
    public var x: kotlin.Int
      @JvmName("getX")
      get() = _builder.x
      @JvmName("setX")
      set(value) {
        _builder.x = value
      }
    /**
     * `int32 x = 1;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `int32 y = 2;`
     */
    public var y: kotlin.Int
      @JvmName("getY")
      get() = _builder.y
      @JvmName("setY")
      set(value) {
        _builder.y = value
      }
    /**
     * `int32 y = 2;`
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * `int32 z = 3;`
     */
    public var z: kotlin.Int
      @JvmName("getZ")
      get() = _builder.z
      @JvmName("setZ")
      set(value) {
        _builder.z = value
      }
    /**
     * `int32 z = 3;`
     */
    public fun clearZ() {
      _builder.clearZ()
    }

    /**
     * `string translation_key = 4;`
     */
    public var translationKey: kotlin.String
      @JvmName("getTranslationKey")
      get() = _builder.translationKey
      @JvmName("setTranslationKey")
      set(value) {
        _builder.translationKey = value
      }
    /**
     * `string translation_key = 4;`
     */
    public fun clearTranslationKey() {
      _builder.clearTranslationKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.BlockInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo =
  `com.kyhsgeekcode.minecraftenv.proto`.BlockInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

