// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializeentityCollisionInfo")
public inline fun entityCollisionInfo(block: com.kyhsgeekcode.minecraftenv.proto.EntityCollisionInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityCollisionInfo =
  com.kyhsgeekcode.minecraftenv.proto.EntityCollisionInfoKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityCollisionInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `EntityCollisionInfo`
 */
public object EntityCollisionInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityCollisionInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityCollisionInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityCollisionInfo = _builder.build()

    /**
     * `float x = 1;`
     */
    public var x: kotlin.Float
      @JvmName("getX")
      get() = _builder.x
      @JvmName("setX")
      set(value) {
        _builder.x = value
      }
    /**
     * `float x = 1;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `float y = 2;`
     */
    public var y: kotlin.Float
      @JvmName("getY")
      get() = _builder.y
      @JvmName("setY")
      set(value) {
        _builder.y = value
      }
    /**
     * `float y = 2;`
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * `float z = 3;`
     */
    public var z: kotlin.Float
      @JvmName("getZ")
      get() = _builder.z
      @JvmName("setZ")
      set(value) {
        _builder.z = value
      }
    /**
     * `float z = 3;`
     */
    public fun clearZ() {
      _builder.clearZ()
    }

    /**
     * `string entity_name = 4;`
     */
    public var entityName: kotlin.String
      @JvmName("getEntityName")
      get() = _builder.entityName
      @JvmName("setEntityName")
      set(value) {
        _builder.entityName = value
      }
    /**
     * `string entity_name = 4;`
     */
    public fun clearEntityName() {
      _builder.clearEntityName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityCollisionInfo.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.EntityCollisionInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityCollisionInfo =
  `com.kyhsgeekcode.minecraftenv.proto`.EntityCollisionInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

