// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializeitemStack")
public inline fun itemStack(block: com.kyhsgeekcode.minecraftenv.proto.ItemStackKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack =
  com.kyhsgeekcode.minecraftenv.proto.ItemStackKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ItemStack`
 */
public object ItemStackKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack = _builder.build()

    /**
     * `int32 raw_id = 1;`
     */
    public var rawId: kotlin.Int
      @JvmName("getRawId")
      get() = _builder.rawId
      @JvmName("setRawId")
      set(value) {
        _builder.rawId = value
      }
    /**
     * `int32 raw_id = 1;`
     */
    public fun clearRawId() {
      _builder.clearRawId()
    }

    /**
     * `string translation_key = 2;`
     */
    public var translationKey: kotlin.String
      @JvmName("getTranslationKey")
      get() = _builder.translationKey
      @JvmName("setTranslationKey")
      set(value) {
        _builder.translationKey = value
      }
    /**
     * `string translation_key = 2;`
     */
    public fun clearTranslationKey() {
      _builder.clearTranslationKey()
    }

    /**
     * `int32 count = 3;`
     */
    public var count: kotlin.Int
      @JvmName("getCount")
      get() = _builder.count
      @JvmName("setCount")
      set(value) {
        _builder.count = value
      }
    /**
     * `int32 count = 3;`
     */
    public fun clearCount() {
      _builder.clearCount()
    }

    /**
     * `int32 durability = 4;`
     */
    public var durability: kotlin.Int
      @JvmName("getDurability")
      get() = _builder.durability
      @JvmName("setDurability")
      set(value) {
        _builder.durability = value
      }
    /**
     * `int32 durability = 4;`
     */
    public fun clearDurability() {
      _builder.clearDurability()
    }

    /**
     * `int32 max_durability = 5;`
     */
    public var maxDurability: kotlin.Int
      @JvmName("getMaxDurability")
      get() = _builder.maxDurability
      @JvmName("setMaxDurability")
      set(value) {
        _builder.maxDurability = value
      }
    /**
     * `int32 max_durability = 5;`
     */
    public fun clearMaxDurability() {
      _builder.clearMaxDurability()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.ItemStackKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack =
  `com.kyhsgeekcode.minecraftenv.proto`.ItemStackKt.Dsl._create(this.toBuilder()).apply { block() }._build()

