// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializelidarResult")
public inline fun lidarResult(block: com.kyhsgeekcode.minecraftenv.proto.LidarResultKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarResult =
  com.kyhsgeekcode.minecraftenv.proto.LidarResultKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `LidarResult`
 */
public object LidarResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarResult = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RaysProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * All raycast results
     * ```
     *
     * `repeated .LidarRay rays = 1;`
     */
     public val rays: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay, RaysProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.raysList
      )
    /**
     * ```
     * All raycast results
     * ```
     *
     * `repeated .LidarRay rays = 1;`
     * @param value The rays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRays")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay, RaysProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay) {
      _builder.addRays(value)
    }
    /**
     * ```
     * All raycast results
     * ```
     *
     * `repeated .LidarRay rays = 1;`
     * @param value The rays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRays")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay, RaysProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay) {
      add(value)
    }
    /**
     * ```
     * All raycast results
     * ```
     *
     * `repeated .LidarRay rays = 1;`
     * @param values The rays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRays")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay, RaysProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay>) {
      _builder.addAllRays(values)
    }
    /**
     * ```
     * All raycast results
     * ```
     *
     * `repeated .LidarRay rays = 1;`
     * @param values The rays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRays")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay, RaysProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay>) {
      addAll(values)
    }
    /**
     * ```
     * All raycast results
     * ```
     *
     * `repeated .LidarRay rays = 1;`
     * @param index The index to set the value at.
     * @param value The rays to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRays")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay, RaysProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay) {
      _builder.setRays(index, value)
    }
    /**
     * ```
     * All raycast results
     * ```
     *
     * `repeated .LidarRay rays = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRays")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay, RaysProxy>.clear() {
      _builder.clearRays()
    }


    /**
     * ```
     * Number of horizontal rays
     * ```
     *
     * `int32 horizontal_rays = 2;`
     */
    public var horizontalRays: kotlin.Int
      @JvmName("getHorizontalRays")
      get() = _builder.horizontalRays
      @JvmName("setHorizontalRays")
      set(value) {
        _builder.horizontalRays = value
      }
    /**
     * ```
     * Number of horizontal rays
     * ```
     *
     * `int32 horizontal_rays = 2;`
     */
    public fun clearHorizontalRays() {
      _builder.clearHorizontalRays()
    }

    /**
     * ```
     * Number of vertical rays
     * ```
     *
     * `int32 vertical_rays = 3;`
     */
    public var verticalRays: kotlin.Int
      @JvmName("getVerticalRays")
      get() = _builder.verticalRays
      @JvmName("setVerticalRays")
      set(value) {
        _builder.verticalRays = value
      }
    /**
     * ```
     * Number of vertical rays
     * ```
     *
     * `int32 vertical_rays = 3;`
     */
    public fun clearVerticalRays() {
      _builder.clearVerticalRays()
    }

    /**
     * ```
     * Maximum distance used
     * ```
     *
     * `float max_distance = 4;`
     */
    public var maxDistance: kotlin.Float
      @JvmName("getMaxDistance")
      get() = _builder.maxDistance
      @JvmName("setMaxDistance")
      set(value) {
        _builder.maxDistance = value
      }
    /**
     * ```
     * Maximum distance used
     * ```
     *
     * `float max_distance = 4;`
     */
    public fun clearMaxDistance() {
      _builder.clearMaxDistance()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarResult.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.LidarResultKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarResult =
  `com.kyhsgeekcode.minecraftenv.proto`.LidarResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

