// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

package com.kyhsgeekcode.minecraftenv.proto

@kotlin.jvm.JvmName("-initializenearbyBiome")
public inline fun nearbyBiome(
    block: com.kyhsgeekcode.minecraftenv.proto.NearbyBiomeKt.Dsl.() -> kotlin.Unit,
): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome =
    com.kyhsgeekcode.minecraftenv.proto.NearbyBiomeKt.Dsl
        ._create(
            com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome
                .newBuilder(),
        ).apply {
            block()
        }._build()

/**
 * Protobuf type `NearbyBiome`
 */
public object NearbyBiomeKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
        private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome.Builder,
    ) {
        public companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome = _builder.build()

        /**
         * `string biome_name = 1;`
         */
        public var biomeName: kotlin.String
            @JvmName("getBiomeName")
            get() = _builder.biomeName

            @JvmName("setBiomeName")
            set(value) {
                _builder.biomeName = value
            }

        /**
         * `string biome_name = 1;`
         */
        public fun clearBiomeName() {
            _builder.clearBiomeName()
        }

        /**
         * `int32 x = 2;`
         */
        public var x: kotlin.Int
            @JvmName("getX")
            get() = _builder.x

            @JvmName("setX")
            set(value) {
                _builder.x = value
            }

        /**
         * `int32 x = 2;`
         */
        public fun clearX() {
            _builder.clearX()
        }

        /**
         * `int32 y = 3;`
         */
        public var y: kotlin.Int
            @JvmName("getY")
            get() = _builder.y

            @JvmName("setY")
            set(value) {
                _builder.y = value
            }

        /**
         * `int32 y = 3;`
         */
        public fun clearY() {
            _builder.clearY()
        }

        /**
         * `int32 z = 4;`
         */
        public var z: kotlin.Int
            @JvmName("getZ")
            get() = _builder.z

            @JvmName("setZ")
            set(value) {
                _builder.z = value
            }

        /**
         * `int32 z = 4;`
         */
        public fun clearZ() {
            _builder.clearZ()
        }
    }
}

@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome.copy(
    block: `com.kyhsgeekcode.minecraftenv.proto`.NearbyBiomeKt.Dsl.() -> kotlin.Unit,
): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome =
    `com.kyhsgeekcode.minecraftenv.proto`.NearbyBiomeKt.Dsl
        ._create(this.toBuilder())
        .apply { block() }
        ._build()
