// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializeobservationSpaceMessage")
public inline fun observationSpaceMessage(block: com.kyhsgeekcode.minecraftenv.proto.ObservationSpaceMessageKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessage =
  com.kyhsgeekcode.minecraftenv.proto.ObservationSpaceMessageKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ObservationSpaceMessage`
 */
public object ObservationSpaceMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessage = _builder.build()

    /**
     * `bytes image = 1;`
     */
    public var image: com.google.protobuf.ByteString
      @JvmName("getImage")
      get() = _builder.image
      @JvmName("setImage")
      set(value) {
        _builder.image = value
      }
    /**
     * `bytes image = 1;`
     */
    public fun clearImage() {
      _builder.clearImage()
    }

    /**
     * `double x = 2;`
     */
    public var x: kotlin.Double
      @JvmName("getX")
      get() = _builder.x
      @JvmName("setX")
      set(value) {
        _builder.x = value
      }
    /**
     * `double x = 2;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `double y = 3;`
     */
    public var y: kotlin.Double
      @JvmName("getY")
      get() = _builder.y
      @JvmName("setY")
      set(value) {
        _builder.y = value
      }
    /**
     * `double y = 3;`
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * `double z = 4;`
     */
    public var z: kotlin.Double
      @JvmName("getZ")
      get() = _builder.z
      @JvmName("setZ")
      set(value) {
        _builder.z = value
      }
    /**
     * `double z = 4;`
     */
    public fun clearZ() {
      _builder.clearZ()
    }

    /**
     * `double yaw = 5;`
     */
    public var yaw: kotlin.Double
      @JvmName("getYaw")
      get() = _builder.yaw
      @JvmName("setYaw")
      set(value) {
        _builder.yaw = value
      }
    /**
     * `double yaw = 5;`
     */
    public fun clearYaw() {
      _builder.clearYaw()
    }

    /**
     * `double pitch = 6;`
     */
    public var pitch: kotlin.Double
      @JvmName("getPitch")
      get() = _builder.pitch
      @JvmName("setPitch")
      set(value) {
        _builder.pitch = value
      }
    /**
     * `double pitch = 6;`
     */
    public fun clearPitch() {
      _builder.clearPitch()
    }

    /**
     * `double health = 7;`
     */
    public var health: kotlin.Double
      @JvmName("getHealth")
      get() = _builder.health
      @JvmName("setHealth")
      set(value) {
        _builder.health = value
      }
    /**
     * `double health = 7;`
     */
    public fun clearHealth() {
      _builder.clearHealth()
    }

    /**
     * `double food_level = 8;`
     */
    public var foodLevel: kotlin.Double
      @JvmName("getFoodLevel")
      get() = _builder.foodLevel
      @JvmName("setFoodLevel")
      set(value) {
        _builder.foodLevel = value
      }
    /**
     * `double food_level = 8;`
     */
    public fun clearFoodLevel() {
      _builder.clearFoodLevel()
    }

    /**
     * `double saturation_level = 9;`
     */
    public var saturationLevel: kotlin.Double
      @JvmName("getSaturationLevel")
      get() = _builder.saturationLevel
      @JvmName("setSaturationLevel")
      set(value) {
        _builder.saturationLevel = value
      }
    /**
     * `double saturation_level = 9;`
     */
    public fun clearSaturationLevel() {
      _builder.clearSaturationLevel()
    }

    /**
     * `bool is_dead = 10;`
     */
    public var isDead: kotlin.Boolean
      @JvmName("getIsDead")
      get() = _builder.isDead
      @JvmName("setIsDead")
      set(value) {
        _builder.isDead = value
      }
    /**
     * `bool is_dead = 10;`
     */
    public fun clearIsDead() {
      _builder.clearIsDead()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InventoryProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ItemStack inventory = 11;`
     */
     public val inventory: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack, InventoryProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.inventoryList
      )
    /**
     * `repeated .ItemStack inventory = 11;`
     * @param value The inventory to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addInventory")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack, InventoryProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack) {
      _builder.addInventory(value)
    }
    /**
     * `repeated .ItemStack inventory = 11;`
     * @param value The inventory to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignInventory")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack, InventoryProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack) {
      add(value)
    }
    /**
     * `repeated .ItemStack inventory = 11;`
     * @param values The inventory to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllInventory")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack, InventoryProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack>) {
      _builder.addAllInventory(values)
    }
    /**
     * `repeated .ItemStack inventory = 11;`
     * @param values The inventory to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllInventory")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack, InventoryProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack>) {
      addAll(values)
    }
    /**
     * `repeated .ItemStack inventory = 11;`
     * @param index The index to set the value at.
     * @param value The inventory to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setInventory")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack, InventoryProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack) {
      _builder.setInventory(index, value)
    }
    /**
     * `repeated .ItemStack inventory = 11;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearInventory")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ItemStack, InventoryProxy>.clear() {
      _builder.clearInventory()
    }


    /**
     * `.HitResult raycast_result = 12;`
     */
    public var raycastResult: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HitResult
      @JvmName("getRaycastResult")
      get() = _builder.raycastResult
      @JvmName("setRaycastResult")
      set(value) {
        _builder.raycastResult = value
      }
    /**
     * `.HitResult raycast_result = 12;`
     */
    public fun clearRaycastResult() {
      _builder.clearRaycastResult()
    }
    /**
     * `.HitResult raycast_result = 12;`
     * @return Whether the raycastResult field is set.
     */
    public fun hasRaycastResult(): kotlin.Boolean {
      return _builder.hasRaycastResult()
    }

    public val ObservationSpaceMessageKt.Dsl.raycastResultOrNull: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HitResult?
      get() = _builder.raycastResultOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SoundSubtitlesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .SoundEntry sound_subtitles = 13;`
     */
     public val soundSubtitles: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry, SoundSubtitlesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.soundSubtitlesList
      )
    /**
     * `repeated .SoundEntry sound_subtitles = 13;`
     * @param value The soundSubtitles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSoundSubtitles")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry, SoundSubtitlesProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry) {
      _builder.addSoundSubtitles(value)
    }
    /**
     * `repeated .SoundEntry sound_subtitles = 13;`
     * @param value The soundSubtitles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSoundSubtitles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry, SoundSubtitlesProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry) {
      add(value)
    }
    /**
     * `repeated .SoundEntry sound_subtitles = 13;`
     * @param values The soundSubtitles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSoundSubtitles")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry, SoundSubtitlesProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry>) {
      _builder.addAllSoundSubtitles(values)
    }
    /**
     * `repeated .SoundEntry sound_subtitles = 13;`
     * @param values The soundSubtitles to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSoundSubtitles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry, SoundSubtitlesProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry>) {
      addAll(values)
    }
    /**
     * `repeated .SoundEntry sound_subtitles = 13;`
     * @param index The index to set the value at.
     * @param value The soundSubtitles to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSoundSubtitles")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry, SoundSubtitlesProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry) {
      _builder.setSoundSubtitles(index, value)
    }
    /**
     * `repeated .SoundEntry sound_subtitles = 13;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSoundSubtitles")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry, SoundSubtitlesProxy>.clear() {
      _builder.clearSoundSubtitles()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class StatusEffectsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .StatusEffect status_effects = 14;`
     */
     public val statusEffects: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect, StatusEffectsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.statusEffectsList
      )
    /**
     * `repeated .StatusEffect status_effects = 14;`
     * @param value The statusEffects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addStatusEffects")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect, StatusEffectsProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect) {
      _builder.addStatusEffects(value)
    }
    /**
     * `repeated .StatusEffect status_effects = 14;`
     * @param value The statusEffects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignStatusEffects")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect, StatusEffectsProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect) {
      add(value)
    }
    /**
     * `repeated .StatusEffect status_effects = 14;`
     * @param values The statusEffects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllStatusEffects")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect, StatusEffectsProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect>) {
      _builder.addAllStatusEffects(values)
    }
    /**
     * `repeated .StatusEffect status_effects = 14;`
     * @param values The statusEffects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllStatusEffects")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect, StatusEffectsProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect>) {
      addAll(values)
    }
    /**
     * `repeated .StatusEffect status_effects = 14;`
     * @param index The index to set the value at.
     * @param value The statusEffects to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setStatusEffects")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect, StatusEffectsProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect) {
      _builder.setStatusEffects(index, value)
    }
    /**
     * `repeated .StatusEffect status_effects = 14;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearStatusEffects")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect, StatusEffectsProxy>.clear() {
      _builder.clearStatusEffects()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KilledStatisticsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, int32> killed_statistics = 15;`
     */
     public val killedStatistics: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, KilledStatisticsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getKilledStatisticsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.killedStatisticsMap
      )
    /**
     * `map<string, int32> killed_statistics = 15;`
     */
    @JvmName("putKilledStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, KilledStatisticsProxy>
      .put(key: kotlin.String, value: kotlin.Int) {
         _builder.putKilledStatistics(key, value)
       }
    /**
     * `map<string, int32> killed_statistics = 15;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setKilledStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, KilledStatisticsProxy>
      .set(key: kotlin.String, value: kotlin.Int) {
         put(key, value)
       }
    /**
     * `map<string, int32> killed_statistics = 15;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeKilledStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, KilledStatisticsProxy>
      .remove(key: kotlin.String) {
         _builder.removeKilledStatistics(key)
       }
    /**
     * `map<string, int32> killed_statistics = 15;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllKilledStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, KilledStatisticsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.Int>) {
         _builder.putAllKilledStatistics(map)
       }
    /**
     * `map<string, int32> killed_statistics = 15;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearKilledStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, KilledStatisticsProxy>
      .clear() {
         _builder.clearKilledStatistics()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MinedStatisticsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, int32> mined_statistics = 16;`
     */
     public val minedStatistics: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MinedStatisticsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getMinedStatisticsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.minedStatisticsMap
      )
    /**
     * `map<string, int32> mined_statistics = 16;`
     */
    @JvmName("putMinedStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MinedStatisticsProxy>
      .put(key: kotlin.String, value: kotlin.Int) {
         _builder.putMinedStatistics(key, value)
       }
    /**
     * `map<string, int32> mined_statistics = 16;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setMinedStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MinedStatisticsProxy>
      .set(key: kotlin.String, value: kotlin.Int) {
         put(key, value)
       }
    /**
     * `map<string, int32> mined_statistics = 16;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeMinedStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MinedStatisticsProxy>
      .remove(key: kotlin.String) {
         _builder.removeMinedStatistics(key)
       }
    /**
     * `map<string, int32> mined_statistics = 16;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllMinedStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MinedStatisticsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.Int>) {
         _builder.putAllMinedStatistics(map)
       }
    /**
     * `map<string, int32> mined_statistics = 16;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearMinedStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MinedStatisticsProxy>
      .clear() {
         _builder.clearMinedStatistics()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MiscStatisticsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, int32> misc_statistics = 17;`
     */
     public val miscStatistics: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MiscStatisticsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getMiscStatisticsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.miscStatisticsMap
      )
    /**
     * `map<string, int32> misc_statistics = 17;`
     */
    @JvmName("putMiscStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MiscStatisticsProxy>
      .put(key: kotlin.String, value: kotlin.Int) {
         _builder.putMiscStatistics(key, value)
       }
    /**
     * `map<string, int32> misc_statistics = 17;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setMiscStatistics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MiscStatisticsProxy>
      .set(key: kotlin.String, value: kotlin.Int) {
         put(key, value)
       }
    /**
     * `map<string, int32> misc_statistics = 17;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeMiscStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MiscStatisticsProxy>
      .remove(key: kotlin.String) {
         _builder.removeMiscStatistics(key)
       }
    /**
     * `map<string, int32> misc_statistics = 17;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllMiscStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MiscStatisticsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.Int>) {
         _builder.putAllMiscStatistics(map)
       }
    /**
     * `map<string, int32> misc_statistics = 17;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearMiscStatistics")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.Int, MiscStatisticsProxy>
      .clear() {
         _builder.clearMiscStatistics()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class VisibleEntitiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .EntityInfo visible_entities = 18;`
     */
     public val visibleEntities: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo, VisibleEntitiesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.visibleEntitiesList
      )
    /**
     * `repeated .EntityInfo visible_entities = 18;`
     * @param value The visibleEntities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addVisibleEntities")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo, VisibleEntitiesProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo) {
      _builder.addVisibleEntities(value)
    }
    /**
     * `repeated .EntityInfo visible_entities = 18;`
     * @param value The visibleEntities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignVisibleEntities")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo, VisibleEntitiesProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo) {
      add(value)
    }
    /**
     * `repeated .EntityInfo visible_entities = 18;`
     * @param values The visibleEntities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllVisibleEntities")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo, VisibleEntitiesProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo>) {
      _builder.addAllVisibleEntities(values)
    }
    /**
     * `repeated .EntityInfo visible_entities = 18;`
     * @param values The visibleEntities to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllVisibleEntities")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo, VisibleEntitiesProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo>) {
      addAll(values)
    }
    /**
     * `repeated .EntityInfo visible_entities = 18;`
     * @param index The index to set the value at.
     * @param value The visibleEntities to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setVisibleEntities")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo, VisibleEntitiesProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo) {
      _builder.setVisibleEntities(index, value)
    }
    /**
     * `repeated .EntityInfo visible_entities = 18;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearVisibleEntities")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntityInfo, VisibleEntitiesProxy>.clear() {
      _builder.clearVisibleEntities()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SurroundingEntitiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<int32, .EntitiesWithinDistance> surrounding_entities = 19;`
     */
     public val surroundingEntities: com.google.protobuf.kotlin.DslMap<kotlin.Int, com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance, SurroundingEntitiesProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getSurroundingEntitiesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.surroundingEntitiesMap
      )
    /**
     * `map<int32, .EntitiesWithinDistance> surrounding_entities = 19;`
     */
    @JvmName("putSurroundingEntities")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance, SurroundingEntitiesProxy>
      .put(key: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance) {
         _builder.putSurroundingEntities(key, value)
       }
    /**
     * `map<int32, .EntitiesWithinDistance> surrounding_entities = 19;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setSurroundingEntities")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.Int, com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance, SurroundingEntitiesProxy>
      .set(key: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance) {
         put(key, value)
       }
    /**
     * `map<int32, .EntitiesWithinDistance> surrounding_entities = 19;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeSurroundingEntities")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance, SurroundingEntitiesProxy>
      .remove(key: kotlin.Int) {
         _builder.removeSurroundingEntities(key)
       }
    /**
     * `map<int32, .EntitiesWithinDistance> surrounding_entities = 19;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllSurroundingEntities")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance, SurroundingEntitiesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.Int, com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance>) {
         _builder.putAllSurroundingEntities(map)
       }
    /**
     * `map<int32, .EntitiesWithinDistance> surrounding_entities = 19;`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearSurroundingEntities")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.Int, com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.EntitiesWithinDistance, SurroundingEntitiesProxy>
      .clear() {
         _builder.clearSurroundingEntities()
       }

    /**
     * `bool bobber_thrown = 20;`
     */
    public var bobberThrown: kotlin.Boolean
      @JvmName("getBobberThrown")
      get() = _builder.bobberThrown
      @JvmName("setBobberThrown")
      set(value) {
        _builder.bobberThrown = value
      }
    /**
     * `bool bobber_thrown = 20;`
     */
    public fun clearBobberThrown() {
      _builder.clearBobberThrown()
    }

    /**
     * `int32 experience = 21;`
     */
    public var experience: kotlin.Int
      @JvmName("getExperience")
      get() = _builder.experience
      @JvmName("setExperience")
      set(value) {
        _builder.experience = value
      }
    /**
     * `int32 experience = 21;`
     */
    public fun clearExperience() {
      _builder.clearExperience()
    }

    /**
     * `int64 world_time = 22;`
     */
    public var worldTime: kotlin.Long
      @JvmName("getWorldTime")
      get() = _builder.worldTime
      @JvmName("setWorldTime")
      set(value) {
        _builder.worldTime = value
      }
    /**
     * `int64 world_time = 22;`
     */
    public fun clearWorldTime() {
      _builder.clearWorldTime()
    }

    /**
     * `string last_death_message = 23;`
     */
    public var lastDeathMessage: kotlin.String
      @JvmName("getLastDeathMessage")
      get() = _builder.lastDeathMessage
      @JvmName("setLastDeathMessage")
      set(value) {
        _builder.lastDeathMessage = value
      }
    /**
     * `string last_death_message = 23;`
     */
    public fun clearLastDeathMessage() {
      _builder.clearLastDeathMessage()
    }

    /**
     * `bytes image_2 = 24;`
     */
    public var image2: com.google.protobuf.ByteString
      @JvmName("getImage2")
      get() = _builder.image2
      @JvmName("setImage2")
      set(value) {
        _builder.image2 = value
      }
    /**
     * `bytes image_2 = 24;`
     */
    public fun clearImage2() {
      _builder.clearImage2()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SurroundingBlocksProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * center, (-1, -1, -1), (0, -1, -1), ...; xyz order: len = 27
     * ```
     *
     * `repeated .BlockInfo surrounding_blocks = 25;`
     */
     public val surroundingBlocks: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo, SurroundingBlocksProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.surroundingBlocksList
      )
    /**
     * ```
     * center, (-1, -1, -1), (0, -1, -1), ...; xyz order: len = 27
     * ```
     *
     * `repeated .BlockInfo surrounding_blocks = 25;`
     * @param value The surroundingBlocks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSurroundingBlocks")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo, SurroundingBlocksProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo) {
      _builder.addSurroundingBlocks(value)
    }
    /**
     * ```
     * center, (-1, -1, -1), (0, -1, -1), ...; xyz order: len = 27
     * ```
     *
     * `repeated .BlockInfo surrounding_blocks = 25;`
     * @param value The surroundingBlocks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSurroundingBlocks")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo, SurroundingBlocksProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo) {
      add(value)
    }
    /**
     * ```
     * center, (-1, -1, -1), (0, -1, -1), ...; xyz order: len = 27
     * ```
     *
     * `repeated .BlockInfo surrounding_blocks = 25;`
     * @param values The surroundingBlocks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSurroundingBlocks")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo, SurroundingBlocksProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo>) {
      _builder.addAllSurroundingBlocks(values)
    }
    /**
     * ```
     * center, (-1, -1, -1), (0, -1, -1), ...; xyz order: len = 27
     * ```
     *
     * `repeated .BlockInfo surrounding_blocks = 25;`
     * @param values The surroundingBlocks to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSurroundingBlocks")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo, SurroundingBlocksProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo>) {
      addAll(values)
    }
    /**
     * ```
     * center, (-1, -1, -1), (0, -1, -1), ...; xyz order: len = 27
     * ```
     *
     * `repeated .BlockInfo surrounding_blocks = 25;`
     * @param index The index to set the value at.
     * @param value The surroundingBlocks to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSurroundingBlocks")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo, SurroundingBlocksProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo) {
      _builder.setSurroundingBlocks(index, value)
    }
    /**
     * ```
     * center, (-1, -1, -1), (0, -1, -1), ...; xyz order: len = 27
     * ```
     *
     * `repeated .BlockInfo surrounding_blocks = 25;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSurroundingBlocks")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockInfo, SurroundingBlocksProxy>.clear() {
      _builder.clearSurroundingBlocks()
    }


    /**
     * `bool eye_in_block = 26;`
     */
    public var eyeInBlock: kotlin.Boolean
      @JvmName("getEyeInBlock")
      get() = _builder.eyeInBlock
      @JvmName("setEyeInBlock")
      set(value) {
        _builder.eyeInBlock = value
      }
    /**
     * `bool eye_in_block = 26;`
     */
    public fun clearEyeInBlock() {
      _builder.clearEyeInBlock()
    }

    /**
     * `bool suffocating = 27;`
     */
    public var suffocating: kotlin.Boolean
      @JvmName("getSuffocating")
      get() = _builder.suffocating
      @JvmName("setSuffocating")
      set(value) {
        _builder.suffocating = value
      }
    /**
     * `bool suffocating = 27;`
     */
    public fun clearSuffocating() {
      _builder.clearSuffocating()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChatMessagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ChatMessageInfo chat_messages = 28;`
     */
     public val chatMessages: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo, ChatMessagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.chatMessagesList
      )
    /**
     * `repeated .ChatMessageInfo chat_messages = 28;`
     * @param value The chatMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addChatMessages")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo, ChatMessagesProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo) {
      _builder.addChatMessages(value)
    }
    /**
     * `repeated .ChatMessageInfo chat_messages = 28;`
     * @param value The chatMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignChatMessages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo, ChatMessagesProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo) {
      add(value)
    }
    /**
     * `repeated .ChatMessageInfo chat_messages = 28;`
     * @param values The chatMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllChatMessages")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo, ChatMessagesProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo>) {
      _builder.addAllChatMessages(values)
    }
    /**
     * `repeated .ChatMessageInfo chat_messages = 28;`
     * @param values The chatMessages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllChatMessages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo, ChatMessagesProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo>) {
      addAll(values)
    }
    /**
     * `repeated .ChatMessageInfo chat_messages = 28;`
     * @param index The index to set the value at.
     * @param value The chatMessages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setChatMessages")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo, ChatMessagesProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo) {
      _builder.setChatMessages(index, value)
    }
    /**
     * `repeated .ChatMessageInfo chat_messages = 28;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearChatMessages")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo, ChatMessagesProxy>.clear() {
      _builder.clearChatMessages()
    }


    /**
     * `.BiomeInfo biome_info = 29;`
     */
    public var biomeInfo: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BiomeInfo
      @JvmName("getBiomeInfo")
      get() = _builder.biomeInfo
      @JvmName("setBiomeInfo")
      set(value) {
        _builder.biomeInfo = value
      }
    /**
     * `.BiomeInfo biome_info = 29;`
     */
    public fun clearBiomeInfo() {
      _builder.clearBiomeInfo()
    }
    /**
     * `.BiomeInfo biome_info = 29;`
     * @return Whether the biomeInfo field is set.
     */
    public fun hasBiomeInfo(): kotlin.Boolean {
      return _builder.hasBiomeInfo()
    }

    public val ObservationSpaceMessageKt.Dsl.biomeInfoOrNull: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BiomeInfo?
      get() = _builder.biomeInfoOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NearbyBiomesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .NearbyBiome nearby_biomes = 30;`
     */
     public val nearbyBiomes: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome, NearbyBiomesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.nearbyBiomesList
      )
    /**
     * `repeated .NearbyBiome nearby_biomes = 30;`
     * @param value The nearbyBiomes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addNearbyBiomes")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome, NearbyBiomesProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome) {
      _builder.addNearbyBiomes(value)
    }
    /**
     * `repeated .NearbyBiome nearby_biomes = 30;`
     * @param value The nearbyBiomes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignNearbyBiomes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome, NearbyBiomesProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome) {
      add(value)
    }
    /**
     * `repeated .NearbyBiome nearby_biomes = 30;`
     * @param values The nearbyBiomes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllNearbyBiomes")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome, NearbyBiomesProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome>) {
      _builder.addAllNearbyBiomes(values)
    }
    /**
     * `repeated .NearbyBiome nearby_biomes = 30;`
     * @param values The nearbyBiomes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllNearbyBiomes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome, NearbyBiomesProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome>) {
      addAll(values)
    }
    /**
     * `repeated .NearbyBiome nearby_biomes = 30;`
     * @param index The index to set the value at.
     * @param value The nearbyBiomes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setNearbyBiomes")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome, NearbyBiomesProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome) {
      _builder.setNearbyBiomes(index, value)
    }
    /**
     * `repeated .NearbyBiome nearby_biomes = 30;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearNearbyBiomes")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.NearbyBiome, NearbyBiomesProxy>.clear() {
      _builder.clearNearbyBiomes()
    }


    /**
     * `bool submerged_in_water = 31;`
     */
    public var submergedInWater: kotlin.Boolean
      @JvmName("getSubmergedInWater")
      get() = _builder.submergedInWater
      @JvmName("setSubmergedInWater")
      set(value) {
        _builder.submergedInWater = value
      }
    /**
     * `bool submerged_in_water = 31;`
     */
    public fun clearSubmergedInWater() {
      _builder.clearSubmergedInWater()
    }

    /**
     * `bool is_in_lava = 32;`
     */
    public var isInLava: kotlin.Boolean
      @JvmName("getIsInLava")
      get() = _builder.isInLava
      @JvmName("setIsInLava")
      set(value) {
        _builder.isInLava = value
      }
    /**
     * `bool is_in_lava = 32;`
     */
    public fun clearIsInLava() {
      _builder.clearIsInLava()
    }

    /**
     * `bool submerged_in_lava = 33;`
     */
    public var submergedInLava: kotlin.Boolean
      @JvmName("getSubmergedInLava")
      get() = _builder.submergedInLava
      @JvmName("setSubmergedInLava")
      set(value) {
        _builder.submergedInLava = value
      }
    /**
     * `bool submerged_in_lava = 33;`
     */
    public fun clearSubmergedInLava() {
      _builder.clearSubmergedInLava()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HeightInfoProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .HeightInfo height_info = 34;`
     */
     public val heightInfo: com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo, HeightInfoProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.heightInfoList
      )
    /**
     * `repeated .HeightInfo height_info = 34;`
     * @param value The heightInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addHeightInfo")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo, HeightInfoProxy>.add(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo) {
      _builder.addHeightInfo(value)
    }
    /**
     * `repeated .HeightInfo height_info = 34;`
     * @param value The heightInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignHeightInfo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo, HeightInfoProxy>.plusAssign(value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo) {
      add(value)
    }
    /**
     * `repeated .HeightInfo height_info = 34;`
     * @param values The heightInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllHeightInfo")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo, HeightInfoProxy>.addAll(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo>) {
      _builder.addAllHeightInfo(values)
    }
    /**
     * `repeated .HeightInfo height_info = 34;`
     * @param values The heightInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllHeightInfo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo, HeightInfoProxy>.plusAssign(values: kotlin.collections.Iterable<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo>) {
      addAll(values)
    }
    /**
     * `repeated .HeightInfo height_info = 34;`
     * @param index The index to set the value at.
     * @param value The heightInfo to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setHeightInfo")
    public operator fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo, HeightInfoProxy>.set(index: kotlin.Int, value: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo) {
      _builder.setHeightInfo(index, value)
    }
    /**
     * `repeated .HeightInfo height_info = 34;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearHeightInfo")
    public fun com.google.protobuf.kotlin.DslList<com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HeightInfo, HeightInfoProxy>.clear() {
      _builder.clearHeightInfo()
    }


    /**
     * `bool is_on_ground = 35;`
     */
    public var isOnGround: kotlin.Boolean
      @JvmName("getIsOnGround")
      get() = _builder.isOnGround
      @JvmName("setIsOnGround")
      set(value) {
        _builder.isOnGround = value
      }
    /**
     * `bool is_on_ground = 35;`
     */
    public fun clearIsOnGround() {
      _builder.clearIsOnGround()
    }

    /**
     * `bool is_touching_water = 36;`
     */
    public var isTouchingWater: kotlin.Boolean
      @JvmName("getIsTouchingWater")
      get() = _builder.isTouchingWater
      @JvmName("setIsTouchingWater")
      set(value) {
        _builder.isTouchingWater = value
      }
    /**
     * `bool is_touching_water = 36;`
     */
    public fun clearIsTouchingWater() {
      _builder.clearIsTouchingWater()
    }

    /**
     * `bytes ipc_handle = 37;`
     */
    public var ipcHandle: com.google.protobuf.ByteString
      @JvmName("getIpcHandle")
      get() = _builder.ipcHandle
      @JvmName("setIpcHandle")
      set(value) {
        _builder.ipcHandle = value
      }
    /**
     * `bytes ipc_handle = 37;`
     */
    public fun clearIpcHandle() {
      _builder.clearIpcHandle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessage.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.ObservationSpaceMessageKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessage =
  `com.kyhsgeekcode.minecraftenv.proto`.ObservationSpaceMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessageOrBuilder.raycastResultOrNull: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.HitResult?
  get() = if (hasRaycastResult()) getRaycastResult() else null

public val com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ObservationSpaceMessageOrBuilder.biomeInfoOrNull: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BiomeInfo?
  get() = if (hasBiomeInfo()) getBiomeInfo() else null

