// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializesoundEntry")
public inline fun soundEntry(block: com.kyhsgeekcode.minecraftenv.proto.SoundEntryKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry =
  com.kyhsgeekcode.minecraftenv.proto.SoundEntryKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `SoundEntry`
 */
public object SoundEntryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry = _builder.build()

    /**
     * `string translate_key = 1;`
     */
    public var translateKey: kotlin.String
      @JvmName("getTranslateKey")
      get() = _builder.translateKey
      @JvmName("setTranslateKey")
      set(value) {
        _builder.translateKey = value
      }
    /**
     * `string translate_key = 1;`
     */
    public fun clearTranslateKey() {
      _builder.clearTranslateKey()
    }

    /**
     * `int64 age = 2;`
     */
    public var age: kotlin.Long
      @JvmName("getAge")
      get() = _builder.age
      @JvmName("setAge")
      set(value) {
        _builder.age = value
      }
    /**
     * `int64 age = 2;`
     */
    public fun clearAge() {
      _builder.clearAge()
    }

    /**
     * `double x = 3;`
     */
    public var x: kotlin.Double
      @JvmName("getX")
      get() = _builder.x
      @JvmName("setX")
      set(value) {
        _builder.x = value
      }
    /**
     * `double x = 3;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `double y = 4;`
     */
    public var y: kotlin.Double
      @JvmName("getY")
      get() = _builder.y
      @JvmName("setY")
      set(value) {
        _builder.y = value
      }
    /**
     * `double y = 4;`
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * `double z = 5;`
     */
    public var z: kotlin.Double
      @JvmName("getZ")
      get() = _builder.z
      @JvmName("setZ")
      set(value) {
        _builder.z = value
      }
    /**
     * `double z = 5;`
     */
    public fun clearZ() {
      _builder.clearZ()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.SoundEntryKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.SoundEntry =
  `com.kyhsgeekcode.minecraftenv.proto`.SoundEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

