# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action_space.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 27, 3, "", "action_space.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x61\x63tion_space.proto"\x9b\x03\n\x14\x41\x63tionSpaceMessageV2\x12\x0e\n\x06\x61ttack\x18\x01 \x01(\x08\x12\x0c\n\x04\x62\x61\x63k\x18\x02 \x01(\x08\x12\x0f\n\x07\x66orward\x18\x03 \x01(\x08\x12\x0c\n\x04jump\x18\x04 \x01(\x08\x12\x0c\n\x04left\x18\x05 \x01(\x08\x12\r\n\x05right\x18\x06 \x01(\x08\x12\r\n\x05sneak\x18\x07 \x01(\x08\x12\x0e\n\x06sprint\x18\x08 \x01(\x08\x12\x0b\n\x03use\x18\t \x01(\x08\x12\x0c\n\x04\x64rop\x18\n \x01(\x08\x12\x11\n\tinventory\x18\x0b \x01(\x08\x12\x10\n\x08hotbar_1\x18\x0c \x01(\x08\x12\x10\n\x08hotbar_2\x18\r \x01(\x08\x12\x10\n\x08hotbar_3\x18\x0e \x01(\x08\x12\x10\n\x08hotbar_4\x18\x0f \x01(\x08\x12\x10\n\x08hotbar_5\x18\x10 \x01(\x08\x12\x10\n\x08hotbar_6\x18\x11 \x01(\x08\x12\x10\n\x08hotbar_7\x18\x12 \x01(\x08\x12\x10\n\x08hotbar_8\x18\x13 \x01(\x08\x12\x10\n\x08hotbar_9\x18\x14 \x01(\x08\x12\x14\n\x0c\x63\x61mera_pitch\x18\x15 \x01(\x02\x12\x12\n\ncamera_yaw\x18\x16 \x01(\x02\x12\x10\n\x08\x63ommands\x18\x17 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "action_space_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ACTIONSPACEMESSAGEV2"]._serialized_start = 23
    _globals["_ACTIONSPACEMESSAGEV2"]._serialized_end = 434
# @@protoc_insertion_point(module_scope)
