# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_space.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x61\x63tion_space.proto"6\n\x12\x41\x63tionSpaceMessage\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x05\x12\x10\n\x08\x63ommands\x18\x02 \x03(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "action_space_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ACTIONSPACEMESSAGE._serialized_start = 22
    _ACTIONSPACEMESSAGE._serialized_end = 76
# @@protoc_insertion_point(module_scope)
