# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: initial_environment.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 3, "", "initial_environment.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19initial_environment.proto"B\n\nBlockState\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\x12\x13\n\x0b\x62lock_state\x18\x04 \x01(\t"\x98\x06\n\x19InitialEnvironmentMessage\x12 \n\x18initialInventoryCommands\x18\x01 \x03(\t\x12\x17\n\x0finitialPosition\x18\x02 \x03(\x05\x12\x1b\n\x13initialMobsCommands\x18\x03 \x03(\t\x12\x12\n\nimageSizeX\x18\x04 \x01(\x05\x12\x12\n\nimageSizeY\x18\x05 \x01(\x05\x12\x0c\n\x04seed\x18\x06 \x01(\x03\x12\x15\n\rallowMobSpawn\x18\x07 \x01(\x08\x12\x13\n\x0b\x61lwaysNight\x18\x08 \x01(\x08\x12\x11\n\talwaysDay\x18\t \x01(\x08\x12\x16\n\x0einitialWeather\x18\n \x01(\t\x12\x13\n\x0bisWorldFlat\x18\x0b \x01(\x08\x12\x14\n\x0cvisibleSizeX\x18\x0c \x01(\x05\x12\x14\n\x0cvisibleSizeY\x18\r \x01(\x05\x12\x1c\n\x14initialExtraCommands\x18\x0e \x03(\t\x12\x16\n\x0ekilledStatKeys\x18\x0f \x03(\t\x12\x15\n\rminedStatKeys\x18\x10 \x03(\t\x12\x14\n\x0cmiscStatKeys\x18\x11 \x03(\t\x12\'\n\x12initialBlockStates\x18\x12 \x03(\x0b\x32\x0b.BlockState\x12"\n\x1asurroundingEntityDistances\x18\x13 \x03(\x05\x12\x11\n\thudHidden\x18\x14 \x01(\x08\x12\x17\n\x0frender_distance\x18\x15 \x01(\x05\x12\x1b\n\x13simulation_distance\x18\x16 \x01(\x05\x12\x10\n\x08\x62iocular\x18\x17 \x01(\x08\x12\x14\n\x0c\x65ye_distance\x18\x18 \x01(\x02\x12\x16\n\x0estructurePaths\x18\x19 \x03(\t\x12\x16\n\x0enoWeatherCycle\x18\x1a \x01(\x08\x12\x15\n\rno_pov_effect\x18\x1b \x01(\x08\x12\x13\n\x0bnoTimeCycle\x18\x1c \x01(\x08\x12\x17\n\x0frequest_raycast\x18\x1d \x01(\x08\x12\x1c\n\x14screen_encoding_mode\x18\x1e \x01(\x05\x12!\n\x19requiresSurroundingBlocks\x18\x1f \x01(\x08\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "initial_environment_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BLOCKSTATE"]._serialized_start = 29
    _globals["_BLOCKSTATE"]._serialized_end = 95
    _globals["_INITIALENVIRONMENTMESSAGE"]._serialized_start = 98
    _globals["_INITIALENVIRONMENTMESSAGE"]._serialized_end = 890
# @@protoc_insertion_point(module_scope)
