// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraft_env.proto;

@kotlin.jvm.JvmName("-initializebiomeInfo")
public inline fun biomeInfo(block: com.kyhsgeekcode.minecraft_env.proto.BiomeInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BiomeInfo =
  com.kyhsgeekcode.minecraft_env.proto.BiomeInfoKt.Dsl._create(com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BiomeInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BiomeInfo`
 */
public object BiomeInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BiomeInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BiomeInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BiomeInfo = _builder.build()

    /**
     * ```
     * 바이옴의 이름
     * ```
     *
     * `string biome_name = 1;`
     */
    public var biomeName: kotlin.String
      @JvmName("getBiomeName")
      get() = _builder.getBiomeName()
      @JvmName("setBiomeName")
      set(value) {
        _builder.setBiomeName(value)
      }
    /**
     * ```
     * 바이옴의 이름
     * ```
     *
     * `string biome_name = 1;`
     */
    public fun clearBiomeName() {
      _builder.clearBiomeName()
    }

    /**
     * ```
     * 바이옴 중심의 x 좌표
     * ```
     *
     * `int32 center_x = 2;`
     */
    public var centerX: kotlin.Int
      @JvmName("getCenterX")
      get() = _builder.getCenterX()
      @JvmName("setCenterX")
      set(value) {
        _builder.setCenterX(value)
      }
    /**
     * ```
     * 바이옴 중심의 x 좌표
     * ```
     *
     * `int32 center_x = 2;`
     */
    public fun clearCenterX() {
      _builder.clearCenterX()
    }

    /**
     * ```
     * 바이옴 중심의 y 좌표
     * ```
     *
     * `int32 center_y = 3;`
     */
    public var centerY: kotlin.Int
      @JvmName("getCenterY")
      get() = _builder.getCenterY()
      @JvmName("setCenterY")
      set(value) {
        _builder.setCenterY(value)
      }
    /**
     * ```
     * 바이옴 중심의 y 좌표
     * ```
     *
     * `int32 center_y = 3;`
     */
    public fun clearCenterY() {
      _builder.clearCenterY()
    }

    /**
     * ```
     * 바이옴 중심의 z 좌표
     * ```
     *
     * `int32 center_z = 4;`
     */
    public var centerZ: kotlin.Int
      @JvmName("getCenterZ")
      get() = _builder.getCenterZ()
      @JvmName("setCenterZ")
      set(value) {
        _builder.setCenterZ(value)
      }
    /**
     * ```
     * 바이옴 중심의 z 좌표
     * ```
     *
     * `int32 center_z = 4;`
     */
    public fun clearCenterZ() {
      _builder.clearCenterZ()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BiomeInfo.copy(block: `com.kyhsgeekcode.minecraft_env.proto`.BiomeInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BiomeInfo =
  `com.kyhsgeekcode.minecraft_env.proto`.BiomeInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

