from .bimodal_a2c import BimodalA2CAlgorithm
from .bimodal_dqn import BimodalDQNAlgorithm
from .bimodal_drqn import BimodalDRQNAlgorithm
from .bimodal_jsrl_dqn import BimodalJSRLDQNAlgorithm
from .sound_a2c import SoundA2CAlgorithm
from .sound_dqn import SoundDQNAlgorithm
from .sound_drqn import SoundDRQNAlgorithm
from .sound_jsrl_dqn import SoundJSRLDQNAlgorithm
from .vision_a2c import VisionA2CAlgorithm
from .vision_dqn import VisionDQNAlgorithm
from .vision_drqn import VisionDRQNAlgorithm
from .vision_jsrl_dqn import VisionJSRLDQNAlgorithm
