// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializeblockCollisionInfo")
public inline fun blockCollisionInfo(block: com.kyhsgeekcode.minecraftenv.proto.BlockCollisionInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockCollisionInfo =
  com.kyhsgeekcode.minecraftenv.proto.BlockCollisionInfoKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockCollisionInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BlockCollisionInfo`
 */
public object BlockCollisionInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockCollisionInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockCollisionInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockCollisionInfo = _builder.build()

    /**
     * `int32 x = 1;`
     */
    public var x: kotlin.Int
      @JvmName("getX")
      get() = _builder.x
      @JvmName("setX")
      set(value) {
        _builder.x = value
      }
    /**
     * `int32 x = 1;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `int32 y = 2;`
     */
    public var y: kotlin.Int
      @JvmName("getY")
      get() = _builder.y
      @JvmName("setY")
      set(value) {
        _builder.y = value
      }
    /**
     * `int32 y = 2;`
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * `int32 z = 3;`
     */
    public var z: kotlin.Int
      @JvmName("getZ")
      get() = _builder.z
      @JvmName("setZ")
      set(value) {
        _builder.z = value
      }
    /**
     * `int32 z = 3;`
     */
    public fun clearZ() {
      _builder.clearZ()
    }

    /**
     * `string block_name = 4;`
     */
    public var blockName: kotlin.String
      @JvmName("getBlockName")
      get() = _builder.blockName
      @JvmName("setBlockName")
      set(value) {
        _builder.blockName = value
      }
    /**
     * `string block_name = 4;`
     */
    public fun clearBlockName() {
      _builder.clearBlockName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockCollisionInfo.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.BlockCollisionInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.BlockCollisionInfo =
  `com.kyhsgeekcode.minecraftenv.proto`.BlockCollisionInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

