// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializechatMessageInfo")
public inline fun chatMessageInfo(block: com.kyhsgeekcode.minecraftenv.proto.ChatMessageInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo =
  com.kyhsgeekcode.minecraftenv.proto.ChatMessageInfoKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ChatMessageInfo`
 */
public object ChatMessageInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo = _builder.build()

    /**
     * `int64 added_time = 1;`
     */
    public var addedTime: kotlin.Long
      @JvmName("getAddedTime")
      get() = _builder.addedTime
      @JvmName("setAddedTime")
      set(value) {
        _builder.addedTime = value
      }
    /**
     * `int64 added_time = 1;`
     */
    public fun clearAddedTime() {
      _builder.clearAddedTime()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.message
      @JvmName("setMessage")
      set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * TODO;; always empty
     * ```
     *
     * `string indicator = 3;`
     */
    public var indicator: kotlin.String
      @JvmName("getIndicator")
      get() = _builder.indicator
      @JvmName("setIndicator")
      set(value) {
        _builder.indicator = value
      }
    /**
     * ```
     * TODO;; always empty
     * ```
     *
     * `string indicator = 3;`
     */
    public fun clearIndicator() {
      _builder.clearIndicator()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.ChatMessageInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.ChatMessageInfo =
  `com.kyhsgeekcode.minecraftenv.proto`.ChatMessageInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

