// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializelidarRay")
public inline fun lidarRay(block: com.kyhsgeekcode.minecraftenv.proto.LidarRayKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay =
  com.kyhsgeekcode.minecraftenv.proto.LidarRayKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `LidarRay`
 */
public object LidarRayKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay = _builder.build()

    /**
     * ```
     * Distance to hit (or max_distance if no hit)
     * ```
     *
     * `float distance = 1;`
     */
    public var distance: kotlin.Float
      @JvmName("getDistance")
      get() = _builder.distance
      @JvmName("setDistance")
      set(value) {
        _builder.distance = value
      }
    /**
     * ```
     * Distance to hit (or max_distance if no hit)
     * ```
     *
     * `float distance = 1;`
     */
    public fun clearDistance() {
      _builder.clearDistance()
    }

    /**
     * ```
     * 0 = MISS, 1 = BLOCK, 2 = ENTITY
     * ```
     *
     * `int32 hit_type = 2;`
     */
    public var hitType: kotlin.Int
      @JvmName("getHitType")
      get() = _builder.hitType
      @JvmName("setHitType")
      set(value) {
        _builder.hitType = value
      }
    /**
     * ```
     * 0 = MISS, 1 = BLOCK, 2 = ENTITY
     * ```
     *
     * `int32 hit_type = 2;`
     */
    public fun clearHitType() {
      _builder.clearHitType()
    }

    /**
     * ```
     * Block translation key if hit_type == BLOCK
     * ```
     *
     * `string block_name = 3;`
     */
    public var blockName: kotlin.String
      @JvmName("getBlockName")
      get() = _builder.blockName
      @JvmName("setBlockName")
      set(value) {
        _builder.blockName = value
      }
    /**
     * ```
     * Block translation key if hit_type == BLOCK
     * ```
     *
     * `string block_name = 3;`
     */
    public fun clearBlockName() {
      _builder.clearBlockName()
    }

    /**
     * ```
     * Entity translation key if hit_type == ENTITY
     * ```
     *
     * `string entity_name = 4;`
     */
    public var entityName: kotlin.String
      @JvmName("getEntityName")
      get() = _builder.entityName
      @JvmName("setEntityName")
      set(value) {
        _builder.entityName = value
      }
    /**
     * ```
     * Entity translation key if hit_type == ENTITY
     * ```
     *
     * `string entity_name = 4;`
     */
    public fun clearEntityName() {
      _builder.clearEntityName()
    }

    /**
     * ```
     * Horizontal angle of this ray in degrees
     * ```
     *
     * `float angle_horizontal = 5;`
     */
    public var angleHorizontal: kotlin.Float
      @JvmName("getAngleHorizontal")
      get() = _builder.angleHorizontal
      @JvmName("setAngleHorizontal")
      set(value) {
        _builder.angleHorizontal = value
      }
    /**
     * ```
     * Horizontal angle of this ray in degrees
     * ```
     *
     * `float angle_horizontal = 5;`
     */
    public fun clearAngleHorizontal() {
      _builder.clearAngleHorizontal()
    }

    /**
     * ```
     * Vertical angle of this ray in degrees
     * ```
     *
     * `float angle_vertical = 6;`
     */
    public var angleVertical: kotlin.Float
      @JvmName("getAngleVertical")
      get() = _builder.angleVertical
      @JvmName("setAngleVertical")
      set(value) {
        _builder.angleVertical = value
      }
    /**
     * ```
     * Vertical angle of this ray in degrees
     * ```
     *
     * `float angle_vertical = 6;`
     */
    public fun clearAngleVertical() {
      _builder.clearAngleVertical()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.LidarRayKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.LidarRay =
  `com.kyhsgeekcode.minecraftenv.proto`.LidarRayKt.Dsl._create(this.toBuilder()).apply { block() }._build()

