// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/observation_space.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kyhsgeekcode.minecraftenv.proto;

@kotlin.jvm.JvmName("-initializestatusEffect")
public inline fun statusEffect(block: com.kyhsgeekcode.minecraftenv.proto.StatusEffectKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect =
  com.kyhsgeekcode.minecraftenv.proto.StatusEffectKt.Dsl._create(com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `StatusEffect`
 */
public object StatusEffectKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect = _builder.build()

    /**
     * `string translation_key = 1;`
     */
    public var translationKey: kotlin.String
      @JvmName("getTranslationKey")
      get() = _builder.translationKey
      @JvmName("setTranslationKey")
      set(value) {
        _builder.translationKey = value
      }
    /**
     * `string translation_key = 1;`
     */
    public fun clearTranslationKey() {
      _builder.clearTranslationKey()
    }

    /**
     * `int32 duration = 2;`
     */
    public var duration: kotlin.Int
      @JvmName("getDuration")
      get() = _builder.duration
      @JvmName("setDuration")
      set(value) {
        _builder.duration = value
      }
    /**
     * `int32 duration = 2;`
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }

    /**
     * `int32 amplifier = 3;`
     */
    public var amplifier: kotlin.Int
      @JvmName("getAmplifier")
      get() = _builder.amplifier
      @JvmName("setAmplifier")
      set(value) {
        _builder.amplifier = value
      }
    /**
     * `int32 amplifier = 3;`
     */
    public fun clearAmplifier() {
      _builder.clearAmplifier()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect.copy(block: `com.kyhsgeekcode.minecraftenv.proto`.StatusEffectKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraftenv.proto.ObservationSpace.StatusEffect =
  `com.kyhsgeekcode.minecraftenv.proto`.StatusEffectKt.Dsl._create(this.toBuilder()).apply { block() }._build()

